"""Learnset Editor — browse and edit Pokemon level-up and egg move learnsets.

Provides a species-first browser: pick a Pokemon, view all its learnable moves,
then add/remove/reorder entries in level-up and egg move lists.

Teachable learnsets (TM/tutor) are displayed read-only since they are
auto-generated by make_teachables.py.

CLI entry: ``torch learnsets``
"""
# TORCH_MODULE: Learnset Editor
# TORCH_GROUP: Data Editors
import os
import re

from torch.colours import GOLD, WHITE, CYAN, DIM, RST, GREEN, RED, BAR
from torch.gamedata import HEADER_MOVES, HEADER_SPECIES, parse_defines, load_species
from torch.ui import _k, clear_screen

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_LEVEL_UP_DIR = os.path.join("src", "data", "pokemon", "level_up_learnsets")
_EGG_MOVES_FILE = os.path.join("src", "data", "pokemon", "egg_moves.h")
_TEACHABLE_FILE = os.path.join("src", "data", "pokemon", "teachable_learnsets.h")

_LEVEL_UP_MOVE_RE = re.compile(
    r'LEVEL_UP_MOVE\(\s*(\d+)\s*,\s*(MOVE_\w+)\s*\)'
)
_ARRAY_START_LEVELUP = re.compile(
    r'^static\s+const\s+struct\s+LevelUpMove\s+s(\w+)LevelUpLearnset\[\]\s*=\s*\{'
)
_ARRAY_START_EGG = re.compile(
    r'^static\s+const\s+u16\s+s(\w+)EggMoveLearnset\[\]\s*=\s*\{'
)
_ARRAY_START_TEACHABLE = re.compile(
    r'^static\s+const\s+u16\s+s(\w+)TeachableLearnset\[\]\s*=\s*\{'
)
_ARRAY_END = re.compile(r'^\s*\};\s*$')


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _format_move_name(move_const):
    """Convert ``MOVE_VINE_WHIP`` to ``Vine Whip``."""
    if not move_const or not move_const.startswith("MOVE_"):
        return move_const or ""
    return move_const[5:].replace("_", " ").title()


def _species_display(species_const):
    """Convert ``SPECIES_BULBASAUR`` to ``Bulbasaur``."""
    if not species_const or not species_const.startswith("SPECIES_"):
        return species_const or ""
    return species_const[8:].replace("_", " ").title()


def _species_to_array_name(species_const):
    """Convert ``SPECIES_BULBASAUR`` to ``Bulbasaur`` (PascalCase for array name).

    Handles multi-word names: ``SPECIES_MR_MIME`` -> ``MrMime``.
    """
    if not species_const or not species_const.startswith("SPECIES_"):
        return species_const or ""
    raw = species_const[8:]
    return "".join(word.capitalize() for word in raw.split("_"))


# ---------------------------------------------------------------------------
# File finding
# ---------------------------------------------------------------------------

def _find_level_up_file(game_path, species_name):
    """Find which gen_*.h file contains this species' level-up learnset.

    *species_name* is the PascalCase array name fragment (e.g. ``Bulbasaur``).
    Returns the full path, or None.
    """
    lu_dir = os.path.join(game_path, _LEVEL_UP_DIR)
    if not os.path.isdir(lu_dir):
        return None
    target = f"s{species_name}LevelUpLearnset"
    for fname in sorted(os.listdir(lu_dir)):
        if not fname.endswith(".h"):
            continue
        fpath = os.path.join(lu_dir, fname)
        try:
            with open(fpath, encoding="utf-8", errors="replace") as f:
                for line in f:
                    if target in line:
                        return fpath
        except OSError:
            continue
    return None


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def _find_array_bounds(lines, pattern):
    """Find start and end line indices for a C array matching *pattern*.

    *pattern* is a compiled regex that matches the array declaration line
    and captures the species name in group 1.

    Returns (start_idx, end_idx, species_match) or (None, None, None).
    start_idx = the line with ``= {``, end_idx = the line with ``};``.
    """
    for i, line in enumerate(lines):
        m = pattern.match(line)
        if m:
            for j in range(i + 1, len(lines)):
                if _ARRAY_END.match(lines[j]):
                    return i, j, m.group(1)
    return None, None, None


def _find_named_array_bounds(lines, array_name_pattern):
    """Find start/end for a specific named array.

    *array_name_pattern* is a compiled regex matching the full declaration.
    Returns (start_idx, end_idx) or (None, None).
    """
    for i, line in enumerate(lines):
        if array_name_pattern.match(line):
            for j in range(i + 1, len(lines)):
                if _ARRAY_END.match(lines[j]):
                    return i, j
    return None, None


def _parse_level_up_learnset(lines, species_name):
    """Extract level-up moves from file lines for a given species.

    Returns list of (level, move_constant) tuples, or empty list.
    """
    target = f"s{species_name}LevelUpLearnset"
    in_array = False
    moves = []
    for line in lines:
        if not in_array:
            if target in line and "=" in line and "{" in line:
                in_array = True
            continue
        if _ARRAY_END.match(line):
            break
        if "LEVEL_UP_END" in line:
            break
        m = _LEVEL_UP_MOVE_RE.search(line)
        if m:
            moves.append((int(m.group(1)), m.group(2)))
    return moves


def _parse_egg_moves(game_path, species_name):
    """Extract egg moves for a species from egg_moves.h.

    Returns list of move constant strings, or empty list.
    """
    egg_path = os.path.join(game_path, _EGG_MOVES_FILE)
    if not os.path.isfile(egg_path):
        return []
    target = f"s{species_name}EggMoveLearnset"
    try:
        with open(egg_path, encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except OSError:
        return []
    in_array = False
    moves = []
    for line in lines:
        if not in_array:
            if target in line and "=" in line and "{" in line:
                in_array = True
            continue
        if _ARRAY_END.match(line):
            break
        stripped = line.strip().rstrip(",").strip()
        if stripped == "MOVE_UNAVAILABLE":
            break
        if stripped.startswith("MOVE_"):
            moves.append(stripped)
    return moves


def _parse_teachable_learnset(game_path, species_name):
    """Extract teachable moves for a species (read-only).

    Returns list of move constant strings, or empty list.
    """
    teach_path = os.path.join(game_path, _TEACHABLE_FILE)
    if not os.path.isfile(teach_path):
        return []
    target = f"s{species_name}TeachableLearnset"
    try:
        with open(teach_path, encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except OSError:
        return []
    in_array = False
    moves = []
    for line in lines:
        if not in_array:
            if target in line and "=" in line and "{" in line:
                in_array = True
            continue
        if _ARRAY_END.match(line):
            break
        stripped = line.strip().rstrip(",").strip()
        if stripped == "MOVE_UNAVAILABLE":
            break
        if stripped.startswith("MOVE_"):
            moves.append(stripped)
    return moves


# ---------------------------------------------------------------------------
# Species list with learnset counts
# ---------------------------------------------------------------------------

def _build_species_list(game_path):
    """Build a lightweight species list with learnset counts.

    Returns list of dicts: {name, display, level_up_count, egg_count, teachable_count}.
    """
    species_raw = load_species(game_path)
    if not species_raw:
        return []

    # Filter to real species only
    skip = {"SPECIES_NONE", "SPECIES_EGG", "SPECIES_UNOWN"}
    skip_prefixes = ("SPECIES_OLD_UNOWN",)
    entries = []
    for name, _comment in species_raw:
        if name in skip:
            continue
        if any(name.startswith(p) for p in skip_prefixes):
            continue
        entries.append(name)

    # Pre-load egg moves file once
    egg_path = os.path.join(game_path, _EGG_MOVES_FILE)
    egg_lines = []
    if os.path.isfile(egg_path):
        try:
            with open(egg_path, encoding="utf-8", errors="replace") as f:
                egg_lines = f.readlines()
        except OSError:
            pass

    # Pre-load teachable file once
    teach_path = os.path.join(game_path, _TEACHABLE_FILE)
    teach_lines = []
    if os.path.isfile(teach_path):
        try:
            with open(teach_path, encoding="utf-8", errors="replace") as f:
                teach_lines = f.readlines()
        except OSError:
            pass

    result = []
    for species in entries:
        array_name = _species_to_array_name(species)
        display = _species_display(species)

        # Count level-up (search file, parse)
        lu_file = _find_level_up_file(game_path, array_name)
        lu_count = 0
        if lu_file:
            try:
                with open(lu_file, encoding="utf-8", errors="replace") as f:
                    lu_lines = f.readlines()
                lu_count = len(_parse_level_up_learnset(lu_lines, array_name))
            except OSError:
                pass

        # Count egg moves from pre-loaded lines
        egg_count = len(_count_moves_in_lines(egg_lines, array_name, "EggMoveLearnset"))

        # Count teachable from pre-loaded lines
        teach_count = len(_count_moves_in_lines(teach_lines, array_name, "TeachableLearnset"))

        result.append({
            "name": species,
            "display": display,
            "level_up_count": lu_count,
            "egg_count": egg_count,
            "teachable_count": teach_count,
        })
    return result


def _count_moves_in_lines(lines, array_name, suffix):
    """Count MOVE_ entries in a named array within pre-loaded lines."""
    target = f"s{array_name}{suffix}"
    in_array = False
    moves = []
    for line in lines:
        if not in_array:
            if target in line and "=" in line and "{" in line:
                in_array = True
            continue
        if _ARRAY_END.match(line):
            break
        stripped = line.strip().rstrip(",").strip()
        if stripped == "MOVE_UNAVAILABLE":
            break
        if stripped.startswith("MOVE_"):
            moves.append(stripped)
    return moves


# ---------------------------------------------------------------------------
# Move picker (search-and-pick from all moves)
# ---------------------------------------------------------------------------

def _pick_move(game_path):
    """Interactive move search-and-pick.

    Uses pickers._search_pick to search all MOVE_* constants.
    Returns the selected move constant string, or None.
    """
    from torch.pickers import _search_pick
    moves = parse_defines(os.path.join(game_path, HEADER_MOVES), "MOVE_")
    # Filter out system moves
    skip = {"MOVE_NONE", "MOVE_UNAVAILABLE", "MOVE_COUNT"}
    filtered = [(n, c) for n, c in moves if n not in skip]
    return _search_pick(filtered, "Move", prefix_strip="MOVE_")


# ---------------------------------------------------------------------------
# Write-back
# ---------------------------------------------------------------------------

def _format_level_up_array(species_name, moves):
    """Format a level-up learnset as C source lines.

    *moves*: list of (level, move_constant) tuples.
    Returns list of strings (each ending with newline).
    """
    sorted_moves = sorted(moves, key=lambda x: (x[0], x[1]))
    lines = [f"static const struct LevelUpMove s{species_name}LevelUpLearnset[] = {{\n"]
    for level, move in sorted_moves:
        lines.append(f"    LEVEL_UP_MOVE({level:2d}, {move}),\n")
    lines.append("    LEVEL_UP_END\n")
    lines.append("};\n")
    return lines


def _format_egg_move_array(species_name, moves):
    """Format an egg move learnset as C source lines.

    *moves*: list of move constant strings.
    Returns list of strings (each ending with newline).
    """
    lines = [f"static const u16 s{species_name}EggMoveLearnset[] = {{\n"]
    for move in moves:
        lines.append(f"    {move},\n")
    lines.append("    MOVE_UNAVAILABLE,\n")
    lines.append("};\n")
    return lines


def _write_level_up_learnset(game_path, species_name, moves):
    """Write an edited level-up learnset back to the correct gen_*.h file.

    Returns True on success, False on failure.
    """
    lu_file = _find_level_up_file(game_path, species_name)
    if not lu_file:
        print(f"  {RED}Could not find level-up learnset file for {species_name}.{RST}")
        return False
    try:
        with open(lu_file, encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except OSError as e:
        print(f"  {RED}Could not read {lu_file}: {e}{RST}")
        return False

    target_re = re.compile(
        r'^static\s+const\s+struct\s+LevelUpMove\s+s'
        + re.escape(species_name)
        + r'LevelUpLearnset\[\]\s*=\s*\{'
    )
    start, end = _find_named_array_bounds(lines, target_re)
    if start is None:
        print(f"  {RED}Could not find array bounds for {species_name} level-up learnset.{RST}")
        return False

    new_array = _format_level_up_array(species_name, moves)
    lines[start:end + 1] = new_array

    try:
        with open(lu_file, "w", encoding="utf-8") as f:
            f.writelines(lines)
    except OSError as e:
        print(f"  {RED}Could not write {lu_file}: {e}{RST}")
        return False

    print(f"  {GREEN}Saved level-up learnset for {species_name} ({len(moves)} moves).{RST}")
    return True


def _write_egg_moves(game_path, species_name, moves):
    """Write edited egg moves back to egg_moves.h.

    Returns True on success, False on failure.
    """
    egg_path = os.path.join(game_path, _EGG_MOVES_FILE)
    if not os.path.isfile(egg_path):
        print(f"  {RED}egg_moves.h not found.{RST}")
        return False
    try:
        with open(egg_path, encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except OSError as e:
        print(f"  {RED}Could not read egg_moves.h: {e}{RST}")
        return False

    target_re = re.compile(
        r'^static\s+const\s+u16\s+s'
        + re.escape(species_name)
        + r'EggMoveLearnset\[\]\s*=\s*\{'
    )
    start, end = _find_named_array_bounds(lines, target_re)
    if start is None:
        print(f"  {RED}Could not find array bounds for {species_name} egg moves.{RST}")
        return False

    new_array = _format_egg_move_array(species_name, moves)
    lines[start:end + 1] = new_array

    try:
        with open(egg_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
    except OSError as e:
        print(f"  {RED}Could not write egg_moves.h: {e}{RST}")
        return False

    print(f"  {GREEN}Saved egg moves for {species_name} ({len(moves)} moves).{RST}")
    return True


# ---------------------------------------------------------------------------
# Interactive editors
# ---------------------------------------------------------------------------

def _lu_add(game_path, working):
    """Add a move to the level-up working list."""
    new_move = _pick_move(game_path)
    if not new_move:
        return
    raw = input(f"  Level (1-100) > ").strip()
    try:
        level = int(raw)
        if 1 <= level <= 100:
            working.append((level, new_move))
            print(f"  Added {_format_move_name(new_move)} at Lv {level}.")
        else:
            print(f"  {DIM}Level must be 1-100.{RST}")
    except ValueError:
        print(f"  {DIM}Invalid level.{RST}")


def _lu_delete(working):
    """Delete a move from the level-up working list."""
    if not working:
        return
    raw = input(f"  Delete # (1-{len(working)}) > ").strip()
    try:
        idx = int(raw) - 1
        if 0 <= idx < len(working):
            removed = working.pop(idx)
            print(f"  Removed {_format_move_name(removed[1])}.")
        else:
            print(f"  {DIM}Pick 1-{len(working)}.{RST}")
    except ValueError:
        print(f"  {DIM}Invalid number.{RST}")


def _lu_edit_level(working):
    """Edit the level of a move in the working list."""
    if not working:
        return
    raw = input(f"  Edit level for # (1-{len(working)}) > ").strip()
    try:
        idx = int(raw) - 1
        if 0 <= idx < len(working):
            new_lvl = input(f"  New level (1-100) > ").strip()
            lvl = int(new_lvl)
            if 1 <= lvl <= 100:
                working[idx] = (lvl, working[idx][1])
                print(f"  Updated to Lv {lvl}.")
            else:
                print(f"  {DIM}Level must be 1-100.{RST}")
        else:
            print(f"  {DIM}Pick 1-{len(working)}.{RST}")
    except ValueError:
        print(f"  {DIM}Invalid input.{RST}")


def _lu_replace(game_path, working):
    """Replace a move in the level-up working list."""
    if not working:
        return
    raw = input(f"  Replace # (1-{len(working)}) > ").strip()
    try:
        idx = int(raw) - 1
        if 0 <= idx < len(working):
            new_move = _pick_move(game_path)
            if new_move:
                working[idx] = (working[idx][0], new_move)
                print(f"  Replaced with {_format_move_name(new_move)}.")
        else:
            print(f"  {DIM}Pick 1-{len(working)}.{RST}")
    except ValueError:
        print(f"  {DIM}Invalid number.{RST}")


def _edit_level_up(game_path, species_name, moves):
    """Interactive level-up move editor.

    *moves*: list of (level, move_constant) tuples (mutable copy).
    Returns the edited list, or None if cancelled.
    """
    display = _species_display("SPECIES_" + species_name.upper())
    working = list(moves)

    while True:
        working.sort(key=lambda x: (x[0], x[1]))
        print()
        print(f"  {WHITE}{display}{RST} {DIM}-- Level-Up Moves{RST}")
        print()
        if working:
            for i, (level, move) in enumerate(working, 1):
                print(f"    {GOLD}{i:>2}.{RST} Lv {level:>2}  {WHITE}{_format_move_name(move):<20}{RST}  {DIM}({move}){RST}")
        else:
            print(f"    {DIM}(no moves){RST}")
        print()
        print(f"  {_k('a')} Add   {_k('d')} Delete   {_k('e')} Edit level   {_k('r')} Replace move")
        print(f"  {_k('c')} Confirm (save)   {_k('q')} Cancel")
        print()
        choice = input(f"  {GOLD}>{RST} ").strip().lower()

        if choice == "q":
            return None
        elif choice == "c":
            return working
        elif choice == "a":
            _lu_add(game_path, working)
        elif choice == "d":
            _lu_delete(working)
        elif choice == "e":
            _lu_edit_level(working)
        elif choice == "r":
            _lu_replace(game_path, working)


def _egg_add(game_path, working):
    """Add a move to the egg move working list."""
    new_move = _pick_move(game_path)
    if not new_move:
        return
    if new_move in working:
        print(f"  {DIM}{_format_move_name(new_move)} is already in the list.{RST}")
    else:
        working.append(new_move)
        print(f"  Added {_format_move_name(new_move)}.")


def _egg_delete(working):
    """Delete a move from the egg move working list."""
    if not working:
        return
    raw = input(f"  Delete # (1-{len(working)}) > ").strip()
    try:
        idx = int(raw) - 1
        if 0 <= idx < len(working):
            removed = working.pop(idx)
            print(f"  Removed {_format_move_name(removed)}.")
        else:
            print(f"  {DIM}Pick 1-{len(working)}.{RST}")
    except ValueError:
        print(f"  {DIM}Invalid number.{RST}")


def _egg_replace(game_path, working):
    """Replace a move in the egg move working list."""
    if not working:
        return
    raw = input(f"  Replace # (1-{len(working)}) > ").strip()
    try:
        idx = int(raw) - 1
        if 0 <= idx < len(working):
            new_move = _pick_move(game_path)
            if new_move:
                working[idx] = new_move
                print(f"  Replaced with {_format_move_name(new_move)}.")
        else:
            print(f"  {DIM}Pick 1-{len(working)}.{RST}")
    except ValueError:
        print(f"  {DIM}Invalid number.{RST}")


def _edit_egg_moves(game_path, species_name, moves):
    """Interactive egg move editor.

    *moves*: list of move constant strings (mutable copy).
    Returns the edited list, or None if cancelled.
    """
    display = _species_display("SPECIES_" + species_name.upper())
    working = list(moves)

    while True:
        print()
        print(f"  {WHITE}{display}{RST} {DIM}-- Egg Moves{RST}")
        print()
        if working:
            for i, move in enumerate(working, 1):
                print(f"    {GOLD}{i:>2}.{RST} {WHITE}{_format_move_name(move):<20}{RST}  {DIM}({move}){RST}")
        else:
            print(f"    {DIM}(no egg moves){RST}")
        print()
        print(f"  {_k('a')} Add   {_k('d')} Delete   {_k('r')} Replace move")
        print(f"  {_k('c')} Confirm (save)   {_k('q')} Cancel")
        print()
        choice = input(f"  {GOLD}>{RST} ").strip().lower()

        if choice == "q":
            return None
        elif choice == "c":
            return working
        elif choice == "a":
            _egg_add(game_path, working)
        elif choice == "d":
            _egg_delete(working)
        elif choice == "r":
            _egg_replace(game_path, working)


# ---------------------------------------------------------------------------
# Learnset view (combined view for one species)
# ---------------------------------------------------------------------------

def _load_all_learnsets(game_path, array_name):
    """Load all three learnset types for a species.

    Returns (lu_moves, egg_moves, teachable).
    """
    lu_file = _find_level_up_file(game_path, array_name)
    lu_moves = []
    if lu_file:
        try:
            with open(lu_file, encoding="utf-8", errors="replace") as f:
                lu_lines = f.readlines()
            lu_moves = _parse_level_up_learnset(lu_lines, array_name)
        except OSError:
            pass
    egg_moves = _parse_egg_moves(game_path, array_name)
    teachable = _parse_teachable_learnset(game_path, array_name)
    return lu_moves, egg_moves, teachable


def _render_learnset_view(display, lu_moves, egg_moves, teachable):
    """Print the combined learnset view for a species."""
    print()
    print(f"  {WHITE}{display}{RST} {DIM}Learnsets{RST}")
    print(BAR)
    print()
    print(f"  {CYAN}Level-Up Moves ({len(lu_moves)}):{RST}")
    if lu_moves:
        sorted_lu = sorted(lu_moves, key=lambda x: (x[0], x[1]))
        for level, move in sorted_lu:
            print(f"    Lv {level:>2}  {WHITE}{_format_move_name(move)}{RST}")
    else:
        print(f"    {DIM}(none){RST}")
    print()
    print(f"  {CYAN}Egg Moves ({len(egg_moves)}):{RST}")
    if egg_moves:
        for move in egg_moves:
            print(f"    {WHITE}{_format_move_name(move)}{RST}")
    else:
        print(f"    {DIM}(none){RST}")
    print()
    if teachable:
        preview = ", ".join(_format_move_name(m) for m in teachable[:8])
        if len(teachable) > 8:
            preview += ", ..."
        print(f"  {CYAN}Teachable ({len(teachable)}, read-only):{RST}  {DIM}{preview}{RST}")
    else:
        print(f"  {CYAN}Teachable (0, read-only){RST}")


def _learnset_view(game_path, species_const, settings):
    """Show all learnset types for a species and offer editing."""
    array_name = _species_to_array_name(species_const)
    display = _species_display(species_const)

    while True:
        lu_moves, egg_moves, teachable = _load_all_learnsets(game_path, array_name)
        _render_learnset_view(display, lu_moves, egg_moves, teachable)

        print()
        print(f"  {_k('l')} Edit level-up   {_k('g')} Edit egg moves   {_k('q')} Back")
        print()
        choice = input(f"  {GOLD}>{RST} ").strip().lower()

        if choice == "q":
            return
        elif choice == "l":
            result = _edit_level_up(game_path, array_name, lu_moves)
            if result is not None:
                _write_level_up_learnset(game_path, array_name, result)
        elif choice == "g":
            result = _edit_egg_moves(game_path, array_name, egg_moves)
            if result is not None:
                _write_egg_moves(game_path, array_name, result)


# ---------------------------------------------------------------------------
# Species picker / main menu
# ---------------------------------------------------------------------------

def _species_search_pick(game_path):
    """Species search-and-pick for learnset editing.

    Returns a SPECIES_* constant, or None.
    """
    from torch.pickers import _search_pick
    species = load_species(game_path)
    skip = {"SPECIES_NONE", "SPECIES_EGG"}
    filtered = [(n, c) for n, c in species if n not in skip]
    return _search_pick(filtered, "Species", prefix_strip="SPECIES_")


def learnset_editor_menu(game_path, settings=None, proj_name=None):
    """Main entry point for the Learnset Editor.

    Called from ``torch learnsets`` or main menu.
    """
    # Version gate: vanilla pokeemerald doesn't use this format
    try:
        from torch.expansion_compat import detect_expansion_version
        version = detect_expansion_version(game_path)
        if version is None:
            print()
            print(f"  {DIM}Learnset Editor requires pokeemerald-expansion.{RST}")
            print(f"  {DIM}Vanilla pokeemerald uses a different learnset format.{RST}")
            input(f"\n  {DIM}Press Enter to return{RST} > ")
            return
    except ImportError:
        pass

    while True:
        print()
        print(f"  {WHITE}TORCH{RST} {DIM}-- Learnset Editor{RST}")
        print()
        print(f"  {DIM}Search for a Pokemon to view and edit its learnsets.{RST}")
        print()
        species = _species_search_pick(game_path)
        if not species:
            return
        _learnset_view(game_path, species, settings)
