# Vanilla reference sets for custom-vs-vanilla asset detection.
# Source: pokeemerald-expansion (quarantine copy)
# Shared across asset_browser, battle_wizard, and any future consumers.

VANILLA_MUSIC = {
    "MUS_LITTLEROOT_TEST",
    "MUS_GSC_ROUTE38",
    "MUS_CAUGHT",
    "MUS_VICTORY_WILD",
    "MUS_VICTORY_GYM_LEADER",
    "MUS_VICTORY_LEAGUE",
    "MUS_C_COMM_CENTER",
    "MUS_GSC_PEWTER",
    "MUS_C_VS_LEGEND_BEAST",
    "MUS_ROUTE101",
    "MUS_ROUTE110",
    "MUS_ROUTE120",
    "MUS_PETALBURG",
    "MUS_OLDALE",
    "MUS_GYM",
    "MUS_SURF",
    "MUS_PETALBURG_WOODS",
    "MUS_LEVEL_UP",
    "MUS_HEAL",
    "MUS_OBTAIN_BADGE",
    "MUS_OBTAIN_ITEM",
    "MUS_EVOLVED",
    "MUS_OBTAIN_TMHM",
    "MUS_LILYCOVE_MUSEUM",
    "MUS_ROUTE122",
    "MUS_OCEANIC_MUSEUM",
    "MUS_EVOLUTION_INTRO",
    "MUS_EVOLUTION",
    "MUS_MOVE_DELETED",
    "MUS_ENCOUNTER_GIRL",
    "MUS_ENCOUNTER_MALE",
    "MUS_ABANDONED_SHIP",
    "MUS_FORTREE",
    "MUS_BIRCH_LAB",
    "MUS_B_TOWER_RS",
    "MUS_ENCOUNTER_SWIMMER",
    "MUS_CAVE_OF_ORIGIN",
    "MUS_OBTAIN_BERRY",
    "MUS_AWAKEN_LEGEND",
    "MUS_SLOTS_JACKPOT",
    "MUS_SLOTS_WIN",
    "MUS_TOO_BAD",
    "MUS_ROULETTE",
    "MUS_LINK_CONTEST_P1",
    "MUS_LINK_CONTEST_P2",
    "MUS_LINK_CONTEST_P3",
    "MUS_LINK_CONTEST_P4",
    "MUS_ENCOUNTER_RICH",
    "MUS_VERDANTURF",
    "MUS_RUSTBORO",
    "MUS_POKE_CENTER",
    "MUS_ROUTE104",
    "MUS_ROUTE119",
    "MUS_CYCLING",
    "MUS_POKE_MART",
    "MUS_LITTLEROOT",
    "MUS_MT_CHIMNEY",
    "MUS_ENCOUNTER_FEMALE",
    "MUS_LILYCOVE",
    "MUS_ROUTE111",
    "MUS_DESERT",
    "MUS_HELP",
    "MUS_UNDERWATER",
    "MUS_VICTORY_TRAINER",
    "MUS_TITLE",
    "MUS_INTRO",
    "MUS_ENCOUNTER_MAY",
    "MUS_ENCOUNTER_INTENSE",
    "MUS_ENCOUNTER_COOL",
    "MUS_ROUTE113",
    "MUS_ENCOUNTER_AQUA",
    "MUS_FOLLOW_ME",
    "MUS_ENCOUNTER_BRENDAN",
    "MUS_EVER_GRANDE",
    "MUS_ENCOUNTER_SUSPICIOUS",
    "MUS_VICTORY_AQUA_MAGMA",
    "MUS_CABLE_CAR",
    "MUS_GAME_CORNER",
    "MUS_DEWFORD",
    "MUS_SAFARI_ZONE",
    "MUS_VICTORY_ROAD",
    "MUS_AQUA_MAGMA_HIDEOUT",
    "MUS_SAILING",
    "MUS_MT_PYRE",
    "MUS_SLATEPORT",
    "MUS_MT_PYRE_EXTERIOR",
    "MUS_SCHOOL",
    "MUS_HALL_OF_FAME",
    "MUS_FALLARBOR",
    "MUS_SEALED_CHAMBER",
    "MUS_CONTEST_WINNER",
    "MUS_CONTEST",
    "MUS_ENCOUNTER_MAGMA",
    "MUS_INTRO_BATTLE",
    "MUS_WEATHER_KYOGRE",
    "MUS_WEATHER_GROUDON",
    "MUS_SOOTOPOLIS",
    "MUS_CONTEST_RESULTS",
    "MUS_HALL_OF_FAME_ROOM",
    "MUS_TRICK_HOUSE",
    "MUS_ENCOUNTER_TWINS",
    "MUS_ENCOUNTER_ELITE_FOUR",
    "MUS_ENCOUNTER_HIKER",
    "MUS_CONTEST_LOBBY",
    "MUS_ENCOUNTER_INTERVIEWER",
    "MUS_ENCOUNTER_CHAMPION",
    "MUS_CREDITS",
    "MUS_END",
    "MUS_VS_WILD",
    "MUS_VS_AQUA_MAGMA",
    "MUS_VS_TRAINER",
    "MUS_VS_GYM_LEADER",
    "MUS_VS_CHAMPION",
    "MUS_VS_REGI",
    "MUS_VS_KYOGRE_GROUDON",
    "MUS_VS_RIVAL",
    "MUS_VS_ELITE_FOUR",
    "MUS_VS_AQUA_MAGMA_LEADER",
    "MUS_RG_FOLLOW_ME",
    "MUS_RG_GAME_CORNER",
    "MUS_RG_ROCKET_HIDEOUT",
    "MUS_RG_GYM",
    "MUS_RG_JIGGLYPUFF",
    "MUS_RG_INTRO_FIGHT",
    "MUS_RG_TITLE",
    "MUS_RG_CINNABAR",
    "MUS_RG_LAVENDER",
    "MUS_RG_HEAL",
    "MUS_RG_CYCLING",
    "MUS_RG_ENCOUNTER_ROCKET",
    "MUS_RG_ENCOUNTER_GIRL",
    "MUS_RG_ENCOUNTER_BOY",
    "MUS_RG_HALL_OF_FAME",
    "MUS_RG_VIRIDIAN_FOREST",
    "MUS_RG_MT_MOON",
    "MUS_RG_POKE_MANSION",
    "MUS_RG_CREDITS",
    "MUS_RG_ROUTE1",
    "MUS_RG_ROUTE24",
    "MUS_RG_ROUTE3",
    "MUS_RG_ROUTE11",
    "MUS_RG_VICTORY_ROAD",
    "MUS_RG_VS_GYM_LEADER",
    "MUS_RG_VS_TRAINER",
    "MUS_RG_VS_WILD",
    "MUS_RG_VS_CHAMPION",
    "MUS_RG_PALLET",
    "MUS_RG_OAK_LAB",
    "MUS_RG_OAK",
    "MUS_RG_POKE_CENTER",
    "MUS_RG_SS_ANNE",
    "MUS_RG_SURF",
    "MUS_RG_POKE_TOWER",
    "MUS_RG_SILPH",
    "MUS_RG_FUCHSIA",
    "MUS_RG_CELADON",
    "MUS_RG_VICTORY_TRAINER",
    "MUS_RG_VICTORY_WILD",
    "MUS_RG_VICTORY_GYM_LEADER",
    "MUS_RG_VERMILLION",
    "MUS_RG_PEWTER",
    "MUS_RG_ENCOUNTER_RIVAL",
    "MUS_RG_RIVAL_EXIT",
    "MUS_RG_DEX_RATING",
    "MUS_RG_OBTAIN_KEY_ITEM",
    "MUS_RG_CAUGHT_INTRO",
    "MUS_RG_PHOTO",
    "MUS_RG_GAME_FREAK",
    "MUS_RG_CAUGHT",
    "MUS_RG_NEW_GAME_INSTRUCT",
    "MUS_RG_NEW_GAME_INTRO",
    "MUS_RG_NEW_GAME_EXIT",
    "MUS_RG_POKE_JUMP",
    "MUS_RG_UNION_ROOM",
    "MUS_RG_NET_CENTER",
    "MUS_RG_MYSTERY_GIFT",
    "MUS_RG_BERRY_PICK",
    "MUS_RG_SEVII_CAVE",
    "MUS_RG_TEACHY_TV_SHOW",
    "MUS_RG_SEVII_ROUTE",
    "MUS_RG_SEVII_DUNGEON",
    "MUS_RG_SEVII_123",
    "MUS_RG_SEVII_45",
    "MUS_RG_SEVII_67",
    "MUS_RG_POKE_FLUTE",
    "MUS_RG_VS_DEOXYS",
    "MUS_RG_VS_MEWTWO",
    "MUS_RG_VS_LEGEND",
    "MUS_RG_ENCOUNTER_GYM_LEADER",
    "MUS_RG_ENCOUNTER_DEOXYS",
    "MUS_RG_TRAINER_TOWER",
    "MUS_RG_SLOW_PALLET",
    "MUS_RG_TEACHY_TV_MENU",
    "MUS_ABNORMAL_WEATHER",
    "MUS_B_FRONTIER",
    "MUS_B_ARENA",
    "MUS_OBTAIN_B_POINTS",
    "MUS_REGISTER_MATCH_CALL",
    "MUS_B_PYRAMID",
    "MUS_B_PYRAMID_TOP",
    "MUS_B_PALACE",
    "MUS_RAYQUAZA_APPEARS",
    "MUS_B_TOWER",
    "MUS_OBTAIN_SYMBOL",
    "MUS_B_DOME",
    "MUS_B_PIKE",
    "MUS_B_FACTORY",
    "MUS_VS_RAYQUAZA",
    "MUS_VS_FRONTIER_BRAIN",
    "MUS_VS_MEW",
    "MUS_B_DOME_LOBBY",
    "MUS_DP_TWINLEAF_DAY",
    "MUS_DP_SANDGEM_DAY",
    "MUS_DP_FLOAROMA_DAY",
    "MUS_DP_SOLACEON_DAY",
    "MUS_DP_ROUTE225_DAY",
    "MUS_DP_VALOR_LAKEFRONT_DAY",
    "MUS_DP_JUBILIFE_DAY",
    "MUS_DP_CANALAVE_DAY",
    "MUS_DP_OREBURGH_DAY",
    "MUS_DP_ETERNA_DAY",
    "MUS_DP_HEARTHOME_DAY",
    "MUS_DP_VEILSTONE_DAY",
    "MUS_DP_SUNYSHORE_DAY",
    "MUS_DP_SNOWPOINT_DAY",
    "MUS_DP_POKEMON_LEAGUE_DAY",
    "MUS_DP_FIGHT_AREA_DAY",
    "MUS_DP_ROUTE201_DAY",
    "MUS_DP_ROUTE203_DAY",
    "MUS_DP_ROUTE205_DAY",
    "MUS_DP_ROUTE206_DAY",
    "MUS_DP_ROUTE209_DAY",
    "MUS_DP_ROUTE210_DAY",
    "MUS_DP_ROUTE216_DAY",
    "MUS_DP_ROUTE228_DAY",
    "MUS_DP_ROWAN",
    "MUS_DP_TV_BROADCAST",
    "MUS_DP_TWINLEAF_NIGHT",
    "MUS_DP_SANDGEM_NIGHT",
    "MUS_DP_FLOAROMA_NIGHT",
    "MUS_DP_SOLACEON_NIGHT",
    "MUS_DP_ROUTE225_NIGHT",
    "MUS_DP_VALOR_LAKEFRONT_NIGHT",
    "MUS_DP_JUBILIFE_NIGHT",
    "MUS_DP_CANALAVE_NIGHT",
    "MUS_DP_OREBURGH_NIGHT",
    "MUS_DP_ETERNA_NIGHT",
    "MUS_DP_HEARTHOME_NIGHT",
    "MUS_DP_VEILSTONE_NIGHT",
    "MUS_DP_SUNYSHORE_NIGHT",
    "MUS_DP_SNOWPOINT_NIGHT",
    "MUS_DP_POKEMON_LEAGUE_NIGHT",
    "MUS_DP_FIGHT_AREA_NIGHT",
    "MUS_DP_ROUTE201_NIGHT",
    "MUS_DP_ROUTE203_NIGHT",
    "MUS_DP_ROUTE205_NIGHT",
    "MUS_DP_ROUTE206_NIGHT",
    "MUS_DP_ROUTE209_NIGHT",
    "MUS_DP_ROUTE210_NIGHT",
    "MUS_DP_ROUTE216_NIGHT",
    "MUS_DP_ROUTE228_NIGHT",
    "MUS_DP_UNDERGROUND",
    "MUS_DP_FLAG_CAPTURED",
    "MUS_DP_VICTORY_ROAD",
    "MUS_DP_ETERNA_FOREST",
    "MUS_DP_OLD_CHATEAU",
    "MUS_DP_LAKE_CAVERNS",
    "MUS_DP_AMITY_SQUARE",
    "MUS_DP_GALACTIC_HQ",
    "MUS_DP_GALACTIC_ETERNA_BUILDING",
    "MUS_DP_GREAT_MARSH",
    "MUS_DP_LAKE",
    "MUS_DP_MT_CORONET",
    "MUS_DP_SPEAR_PILLAR",
    "MUS_DP_STARK_MOUNTAIN",
    "MUS_DP_OREBURGH_GATE",
    "MUS_DP_OREBURGH_MINE",
    "MUS_DP_INSIDE_POKEMON_LEAGUE",
    "MUS_DP_HALL_OF_FAME_ROOM",
    "MUS_DP_POKE_CENTER_DAY",
    "MUS_DP_POKE_CENTER_NIGHT",
    "MUS_DP_GYM",
    "MUS_DP_ROWAN_LAB",
    "MUS_DP_CONTEST_LOBBY",
    "MUS_DP_POKE_MART",
    "MUS_DP_GAME_CORNER",
    "MUS_DP_B_TOWER",
    "MUS_DP_TV_STATION",
    "MUS_DP_GALACTIC_HQ_BASEMENT",
    "MUS_DP_AZURE_FLUTE",
    "MUS_DP_HALL_OF_ORIGIN",
    "MUS_DP_GTS",
    "MUS_DP_ENCOUNTER_BOY",
    "MUS_DP_ENCOUNTER_TWINS",
    "MUS_DP_ENCOUNTER_INTENSE",
    "MUS_DP_ENCOUNTER_GALACTIC",
    "MUS_DP_ENCOUNTER_LADY",
    "MUS_DP_ENCOUNTER_HIKER",
    "MUS_DP_ENCOUNTER_RICH",
    "MUS_DP_ENCOUNTER_SAILOR",
    "MUS_DP_ENCOUNTER_SUSPICIOUS",
    "MUS_DP_ENCOUNTER_ACE_TRAINER",
    "MUS_DP_ENCOUNTER_GIRL",
    "MUS_DP_ENCOUNTER_CYCLIST",
    "MUS_DP_ENCOUNTER_ARTIST",
    "MUS_DP_ENCOUNTER_ELITE_FOUR",
    "MUS_DP_ENCOUNTER_CHAMPION",
    "MUS_DP_VS_WILD",
    "MUS_DP_VS_GYM_LEADER",
    "MUS_DP_VS_UXIE_MESPRIT_AZELF",
    "MUS_DP_VS_TRAINER",
    "MUS_DP_VS_GALACTIC_BOSS",
    "MUS_DP_VS_DIALGA_PALKIA",
    "MUS_DP_VS_CHAMPION",
    "MUS_DP_VS_GALACTIC",
    "MUS_DP_VS_RIVAL",
    "MUS_DP_VS_ARCEUS",
    "MUS_DP_VS_LEGEND",
    "MUS_DP_VICTORY_WILD",
    "MUS_DP_VICTORY_TRAINER",
    "MUS_DP_VICTORY_GYM_LEADER",
    "MUS_DP_VICTORY_CHAMPION",
    "MUS_DP_VICTORY_GALACTIC",
    "MUS_DP_VICTORY_ELITE_FOUR",
    "MUS_DP_VS_GALACTIC_COMMANDER",
    "MUS_DP_CONTEST",
    "MUS_DP_VS_ELITE_FOUR",
    "MUS_DP_FOLLOW_ME",
    "MUS_DP_RIVAL",
    "MUS_DP_LAKE_EVENT",
    "MUS_DP_EVOLUTION",
    "MUS_DP_LUCAS",
    "MUS_DP_DAWN",
    "MUS_DP_LEGEND_APPEARS",
    "MUS_DP_CATASTROPHE",
    "MUS_DP_POKE_RADAR",
    "MUS_DP_SURF",
    "MUS_DP_CYCLING",
    "MUS_DP_LETS_GO_TOGETHER",
    "MUS_DP_TV_END",
    "MUS_DP_LEVEL_UP",
    "MUS_DP_EVOLVED",
    "MUS_DP_OBTAIN_KEY_ITEM",
    "MUS_DP_OBTAIN_ITEM",
    "MUS_DP_CAUGHT_INTRO",
    "MUS_DP_DEX_RATING",
    "MUS_DP_OBTAIN_BADGE",
    "MUS_DP_POKETCH",
    "MUS_DP_OBTAIN_TMHM",
    "MUS_DP_OBTAIN_ACCESSORY",
    "MUS_DP_MOVE_DELETED",
    "MUS_DP_HEAL",
    "MUS_DP_OBTAIN_BERRY",
    "MUS_DP_CONTEST_DRESS_UP",
    "MUS_DP_HALL_OF_FAME",
    "MUS_DP_INTRO",
    "MUS_DP_TITLE",
    "MUS_DP_MYSTERY_GIFT",
    "MUS_DP_WFC",
    "MUS_DP_DANCE_EASY",
    "MUS_DP_DANCE_DIFFICULT",
    "MUS_DP_CONTEST_RESULTS",
    "MUS_DP_CONTEST_WINNER",
    "MUS_DP_POFFINS",
    "MUS_DP_SLOTS_WIN",
    "MUS_DP_SLOTS_JACKPOT",
    "MUS_DP_CREDITS",
    "MUS_DP_SLOTS_UNUSED",
    "MUS_PL_FIGHT_AREA_DAY",
    "MUS_PL_TV_BROADCAST",
    "MUS_PL_TV_END",
    "MUS_PL_INTRO",
    "MUS_PL_TITLE",
    "MUS_PL_DISTORTION_WORLD",
    "MUS_PL_B_ARCADE",
    "MUS_PL_B_HALL",
    "MUS_PL_B_CASTLE",
    "MUS_PL_B_FACTORY",
    "MUS_PL_GLOBAL_TERMINAL",
    "MUS_PL_LILYCOVE_BOSSA_NOVA",
    "MUS_PL_LOOKER",
    "MUS_PL_VS_GIRATINA",
    "MUS_PL_VS_FRONTIER_BRAIN",
    "MUS_PL_VICTORY_FRONTIER_BRAIN",
    "MUS_PL_VS_REGI",
    "MUS_PL_CONTEST_COOL",
    "MUS_PL_CONTEST_SMART",
    "MUS_PL_CONTEST_CUTE",
    "MUS_PL_CONTEST_TOUGH",
    "MUS_PL_CONTEST_BEAUTY",
    "MUS_PL_SPIN_TRADE",
    "MUS_PL_WIFI_MINIGAMES",
    "MUS_PL_WIFI_PLAZA",
    "MUS_PL_WIFI_PARADE",
    "MUS_PL_GIRATINA_APPEARS_1",
    "MUS_PL_GIRATINA_APPEARS_2",
    "MUS_PL_MYSTERY_GIFT",
    "MUS_PL_TWINLEAF_MUSIC_BOX",
    "MUS_PL_OBTAIN_ARCADE_POINTS",
    "MUS_PL_OBTAIN_CASTLE_POINTS",
    "MUS_PL_OBTAIN_B_POINTS",
    "MUS_PL_WIN_MINIGAME",
    "MUS_HG_INTRO",
    "MUS_HG_TITLE",
    "MUS_HG_NEW_GAME",
    "MUS_HG_EVOLUTION",
    "MUS_HG_EVOLUTION_NO_INTRO",
    "MUS_HG_CYCLING",
    "MUS_HG_SURF",
    "MUS_HG_E_DENDOURIRI",
    "MUS_HG_CREDITS",
    "MUS_HG_END",
    "MUS_HG_NEW_BARK",
    "MUS_HG_CHERRYGROVE",
    "MUS_HG_VIOLET",
    "MUS_HG_AZALEA",
    "MUS_HG_GOLDENROD",
    "MUS_HG_ECRUTEAK",
    "MUS_HG_CIANWOOD",
    "MUS_HG_ROUTE29",
    "MUS_HG_ROUTE30",
    "MUS_HG_ROUTE34",
    "MUS_HG_ROUTE38",
    "MUS_HG_ROUTE42",
    "MUS_HG_VERMILION",
    "MUS_HG_PEWTER",
    "MUS_HG_CERULEAN",
    "MUS_HG_LAVENDER",
    "MUS_HG_CELADON",
    "MUS_HG_PALLET",
    "MUS_HG_CINNABAR",
    "MUS_HG_ROUTE1",
    "MUS_HG_ROUTE3",
    "MUS_HG_ROUTE11",
    "MUS_HG_ROUTE24",
    "MUS_HG_ROUTE26",
    "MUS_HG_POKE_CENTER",
    "MUS_HG_POKE_MART",
    "MUS_HG_GYM",
    "MUS_HG_ELM_LAB",
    "MUS_HG_OAK",
    "MUS_HG_DANCE_THEATER",
    "MUS_HG_GAME_CORNER",
    "MUS_HG_B_TOWER",
    "MUS_HG_B_TOWER_RECEPTION",
    "MUS_HG_SPROUT_TOWER",
    "MUS_HG_UNION_CAVE",
    "MUS_HG_RUINS_OF_ALPH",
    "MUS_HG_NATIONAL_PARK",
    "MUS_HG_BURNED_TOWER",
    "MUS_HG_BELL_TOWER",
    "MUS_HG_LIGHTHOUSE",
    "MUS_HG_TEAM_ROCKET_HQ",
    "MUS_HG_ICE_PATH",
    "MUS_HG_DRAGONS_DEN",
    "MUS_HG_ROCK_TUNNEL",
    "MUS_HG_VIRIDIAN_FOREST",
    "MUS_HG_VICTORY_ROAD",
    "MUS_HG_POKEMON_LEAGUE",
    "MUS_HG_FOLLOW_ME_1",
    "MUS_HG_FOLLOW_ME_2",
    "MUS_HG_ENCOUNTER_RIVAL",
    "MUS_HG_RIVAL_EXIT",
    "MUS_HG_BUG_CONTEST_PREP",
    "MUS_HG_BUG_CATCHING_CONTEST",
    "MUS_HG_RADIO_ROCKET",
    "MUS_HG_ROCKET_TAKEOVER",
    "MUS_HG_MAGNET_TRAIN",
    "MUS_HG_SS_AQUA",
    "MUS_HG_MT_MOON_SQUARE",
    "MUS_HG_RADIO_JINGLE",
    "MUS_HG_RADIO_LULLABY",
    "MUS_HG_RADIO_MARCH",
    "MUS_HG_RADIO_UNOWN",
    "MUS_HG_RADIO_POKE_FLUTE",
    "MUS_HG_RADIO_OAK",
    "MUS_HG_RADIO_BUENA",
    "MUS_HG_EUSINE",
    "MUS_HG_CLAIR",
    "MUS_HG_ENCOUNTER_GIRL_1",
    "MUS_HG_ENCOUNTER_BOY_1",
    "MUS_HG_ENCOUNTER_SUSPICIOUS_1",
    "MUS_HG_ENCOUNTER_SAGE",
    "MUS_HG_ENCOUNTER_KIMONO_GIRL",
    "MUS_HG_ENCOUNTER_ROCKET",
    "MUS_HG_ENCOUNTER_GIRL_2",
    "MUS_HG_ENCOUNTER_BOY_2",
    "MUS_HG_ENCOUNTER_SUSPICIOUS_2",
    "MUS_HG_VS_WILD",
    "MUS_HG_VS_TRAINER",
    "MUS_HG_VS_GYM_LEADER",
    "MUS_HG_VS_RIVAL",
    "MUS_HG_VS_ROCKET",
    "MUS_HG_VS_SUICUNE",
    "MUS_HG_VS_ENTEI",
    "MUS_HG_VS_RAIKOU",
    "MUS_HG_VS_CHAMPION",
    "MUS_HG_VS_WILD_KANTO",
    "MUS_HG_VS_TRAINER_KANTO",
    "MUS_HG_VS_GYM_LEADER_KANTO",
    "MUS_HG_VICTORY_TRAINER",
    "MUS_HG_VICTORY_WILD",
    "MUS_HG_CAUGHT",
    "MUS_HG_VICTORY_GYM_LEADER",
    "MUS_HG_VS_HO_OH",
    "MUS_HG_VS_LUGIA",
    "MUS_HG_POKEATHLON_LOBBY",
    "MUS_HG_POKEATHLON_START",
    "MUS_HG_POKEATHLON_BEFORE",
    "MUS_HG_POKEATHLON_EVENT",
    "MUS_HG_POKEATHLON_FINALS",
    "MUS_HG_POKEATHLON_RESULTS",
    "MUS_HG_POKEATHLON_END",
    "MUS_HG_POKEATHLON_WINNER",
    "MUS_HG_B_FACTORY",
    "MUS_HG_B_HALL",
    "MUS_HG_B_ARCADE",
    "MUS_HG_B_CASTLE",
    "MUS_HG_VS_FRONTIER_BRAIN",
    "MUS_HG_VICTORY_FRONTIER_BRAIN",
    "MUS_HG_WFC",
    "MUS_HG_MYSTERY_GIFT",
    "MUS_HG_WIFI_PLAZA",
    "MUS_HG_WIFI_MINIGAMES",
    "MUS_HG_WIFI_PARADE",
    "MUS_HG_GLOBAL_TERMINAL",
    "MUS_HG_SPIN_TRADE",
    "MUS_HG_GTS",
    "MUS_HG_ROUTE47",
    "MUS_HG_SAFARI_ZONE_GATE",
    "MUS_HG_SAFARI_ZONE",
    "MUS_HG_ETHAN",
    "MUS_HG_LYRA",
    "MUS_HG_GAME_CORNER_WIN",
    "MUS_HG_KIMONO_GIRL_DANCE",
    "MUS_HG_KIMONO_GIRL",
    "MUS_HG_HO_OH_APPEARS",
    "MUS_HG_LUGIA_APPEARS",
    "MUS_HG_SPIKY_EARED_PICHU",
    "MUS_HG_SINJOU_RUINS",
    "MUS_HG_RADIO_ROUTE101",
    "MUS_HG_RADIO_ROUTE201",
    "MUS_HG_RADIO_TRAINER",
    "MUS_HG_RADIO_VARIETY",
    "MUS_HG_VS_KYOGRE_GROUDON",
    "MUS_HG_POKEWALKER",
    "MUS_HG_VS_ARCEUS",
    "MUS_HG_HEAL",
    "MUS_HG_LEVEL_UP",
    "MUS_HG_OBTAIN_ITEM",
    "MUS_HG_OBTAIN_KEY_ITEM",
    "MUS_HG_EVOLVED",
    "MUS_HG_OBTAIN_BADGE",
    "MUS_HG_OBTAIN_TMHM",
    "MUS_HG_OBTAIN_ACCESSORY",
    "MUS_HG_MOVE_DELETED",
    "MUS_HG_OBTAIN_BERRY",
    "MUS_HG_DEX_RATING_1",
    "MUS_HG_DEX_RATING_2",
    "MUS_HG_DEX_RATING_3",
    "MUS_HG_DEX_RATING_4",
    "MUS_HG_DEX_RATING_5",
    "MUS_HG_DEX_RATING_6",
    "MUS_HG_OBTAIN_EGG",
    "MUS_HG_BUG_CONTEST_1ST_PLACE",
    "MUS_HG_BUG_CONTEST_2ND_PLACE",
    "MUS_HG_BUG_CONTEST_3RD_PLACE",
    "MUS_HG_CARD_FLIP",
    "MUS_HG_CARD_FLIP_GAME_OVER",
    "MUS_HG_POKEGEAR_REGISTERED",
    "MUS_HG_LETS_GO_TOGETHER",
    "MUS_HG_POKEATHLON_READY",
    "MUS_HG_POKEATHLON_1ST_PLACE",
    "MUS_HG_RECEIVE_POKEMON",
    "MUS_HG_OBTAIN_ARCADE_POINTS",
    "MUS_HG_OBTAIN_CASTLE_POINTS",
    "MUS_HG_OBTAIN_B_POINTS",
    "MUS_HG_WIN_MINIGAME",
    "MUS_ROUTE118",
}

VANILLA_SOUND_EFFECTS = {
    "SE_USE_ITEM",
    "SE_PC_LOGIN",
    "SE_PC_OFF",
    "SE_PC_ON",
    "SE_SELECT",
    "SE_WIN_OPEN",
    "SE_WALL_HIT",
    "SE_DOOR",
    "SE_EXIT",
    "SE_LEDGE",
    "SE_BIKE_BELL",
    "SE_NOT_EFFECTIVE",
    "SE_EFFECTIVE",
    "SE_SUPER_EFFECTIVE",
    "SE_BALL_OPEN",
    "SE_FAINT",
    "SE_FLEE",
    "SE_SLIDING_DOOR",
    "SE_SHIP",
    "SE_BANG",
    "SE_PIN",
    "SE_BOO",
    "SE_BALL",
    "SE_CONTEST_PLACE",
    "SE_A",
    "SE_I",
    "SE_U",
    "SE_E",
    "SE_O",
    "SE_N",
    "SE_SUCCESS",
    "SE_FAILURE",
    "SE_EXP",
    "SE_BIKE_HOP",
    "SE_SWITCH",
    "SE_CLICK",
    "SE_FU_ZAKU",
    "SE_CONTEST_CONDITION_LOSE",
    "SE_LAVARIDGE_FALL_WARP",
    "SE_ICE_STAIRS",
    "SE_ICE_BREAK",
    "SE_ICE_CRACK",
    "SE_FALL",
    "SE_UNLOCK",
    "SE_WARP_IN",
    "SE_WARP_OUT",
    "SE_REPEL",
    "SE_ROTATING_GATE",
    "SE_TRUCK_MOVE",
    "SE_TRUCK_STOP",
    "SE_TRUCK_UNLOAD",
    "SE_TRUCK_DOOR",
    "SE_BERRY_BLENDER",
    "SE_CARD",
    "SE_SAVE",
    "SE_BALL_BOUNCE_1",
    "SE_BALL_BOUNCE_2",
    "SE_BALL_BOUNCE_3",
    "SE_BALL_BOUNCE_4",
    "SE_BALL_TRADE",
    "SE_BALL_THROW",
    "SE_NOTE_C",
    "SE_NOTE_D",
    "SE_NOTE_E",
    "SE_NOTE_F",
    "SE_NOTE_G",
    "SE_NOTE_A",
    "SE_NOTE_B",
    "SE_NOTE_C_HIGH",
    "SE_PUDDLE",
    "SE_BRIDGE_WALK",
    "SE_ITEMFINDER",
    "SE_DING_DONG",
    "SE_BALLOON_RED",
    "SE_BALLOON_BLUE",
    "SE_BALLOON_YELLOW",
    "SE_BREAKABLE_DOOR",
    "SE_MUD_BALL",
    "SE_FIELD_POISON",
    "SE_ESCALATOR",
    "SE_THUNDERSTORM",
    "SE_THUNDERSTORM_STOP",
    "SE_DOWNPOUR",
    "SE_DOWNPOUR_STOP",
    "SE_RAIN",
    "SE_RAIN_STOP",
    "SE_THUNDER",
    "SE_THUNDER2",
    "SE_ELEVATOR",
    "SE_LOW_HEALTH",
    "SE_EXP_MAX",
    "SE_ROULETTE_BALL",
    "SE_ROULETTE_BALL2",
    "SE_TAILLOW_WING_FLAP",
    "SE_SHOP",
    "SE_CONTEST_HEART",
    "SE_CONTEST_CURTAIN_RISE",
    "SE_CONTEST_CURTAIN_FALL",
    "SE_CONTEST_ICON_CHANGE",
    "SE_CONTEST_ICON_CLEAR",
    "SE_CONTEST_MONS_TURN",
    "SE_SHINY",
    "SE_INTRO_BLAST",
    "SE_MUGSHOT",
    "SE_APPLAUSE",
    "SE_VEND",
    "SE_ORB",
    "SE_DEX_SCROLL",
    "SE_DEX_PAGE",
    "SE_POKENAV_ON",
    "SE_POKENAV_OFF",
    "SE_DEX_SEARCH",
    "SE_EGG_HATCH",
    "SE_BALL_TRAY_ENTER",
    "SE_BALL_TRAY_BALL",
    "SE_BALL_TRAY_EXIT",
    "SE_GLASS_FLUTE",
    "SE_M_THUNDERBOLT",
    "SE_M_THUNDERBOLT2",
    "SE_M_HARDEN",
    "SE_M_NIGHTMARE",
    "SE_M_VITAL_THROW",
    "SE_M_VITAL_THROW2",
    "SE_M_BUBBLE",
    "SE_M_BUBBLE2",
    "SE_M_BUBBLE3",
    "SE_M_RAIN_DANCE",
    "SE_M_CUT",
    "SE_M_STRING_SHOT",
    "SE_M_STRING_SHOT2",
    "SE_M_ROCK_THROW",
    "SE_M_GUST",
    "SE_M_GUST2",
    "SE_M_DOUBLE_SLAP",
    "SE_M_DOUBLE_TEAM",
    "SE_M_RAZOR_WIND",
    "SE_M_ICY_WIND",
    "SE_M_THUNDER_WAVE",
    "SE_M_COMET_PUNCH",
    "SE_M_MEGA_KICK",
    "SE_M_MEGA_KICK2",
    "SE_M_CRABHAMMER",
    "SE_M_JUMP_KICK",
    "SE_M_FLAME_WHEEL",
    "SE_M_FLAME_WHEEL2",
    "SE_M_FLAMETHROWER",
    "SE_M_FIRE_PUNCH",
    "SE_M_TOXIC",
    "SE_M_SACRED_FIRE",
    "SE_M_SACRED_FIRE2",
    "SE_M_EMBER",
    "SE_M_TAKE_DOWN",
    "SE_M_BLIZZARD",
    "SE_M_BLIZZARD2",
    "SE_M_SCRATCH",
    "SE_M_VICEGRIP",
    "SE_M_WING_ATTACK",
    "SE_M_FLY",
    "SE_M_SAND_ATTACK",
    "SE_M_RAZOR_WIND2",
    "SE_M_BITE",
    "SE_M_HEADBUTT",
    "SE_M_SURF",
    "SE_M_HYDRO_PUMP",
    "SE_M_WHIRLPOOL",
    "SE_M_HORN_ATTACK",
    "SE_M_TAIL_WHIP",
    "SE_M_MIST",
    "SE_M_POISON_POWDER",
    "SE_M_BIND",
    "SE_M_DRAGON_RAGE",
    "SE_M_SING",
    "SE_M_PERISH_SONG",
    "SE_M_PAY_DAY",
    "SE_M_DIG",
    "SE_M_DIZZY_PUNCH",
    "SE_M_SELF_DESTRUCT",
    "SE_M_EXPLOSION",
    "SE_M_ABSORB_2",
    "SE_M_ABSORB",
    "SE_M_SCREECH",
    "SE_M_BUBBLE_BEAM",
    "SE_M_BUBBLE_BEAM2",
    "SE_M_SUPERSONIC",
    "SE_M_BELLY_DRUM",
    "SE_M_METRONOME",
    "SE_M_BONEMERANG",
    "SE_M_LICK",
    "SE_M_PSYBEAM",
    "SE_M_FAINT_ATTACK",
    "SE_M_SWORDS_DANCE",
    "SE_M_LEER",
    "SE_M_SWAGGER",
    "SE_M_SWAGGER2",
    "SE_M_HEAL_BELL",
    "SE_M_CONFUSE_RAY",
    "SE_M_SNORE",
    "SE_M_BRICK_BREAK",
    "SE_M_GIGA_DRAIN",
    "SE_M_PSYBEAM2",
    "SE_M_SOLAR_BEAM",
    "SE_M_PETAL_DANCE",
    "SE_M_TELEPORT",
    "SE_M_MINIMIZE",
    "SE_M_SKETCH",
    "SE_M_SWIFT",
    "SE_M_REFLECT",
    "SE_M_BARRIER",
    "SE_M_DETECT",
    "SE_M_LOCK_ON",
    "SE_M_MOONLIGHT",
    "SE_M_CHARM",
    "SE_M_CHARGE",
    "SE_M_STRENGTH",
    "SE_M_HYPER_BEAM",
    "SE_M_WATERFALL",
    "SE_M_REVERSAL",
    "SE_M_ACID_ARMOR",
    "SE_M_SANDSTORM",
    "SE_M_TRI_ATTACK",
    "SE_M_TRI_ATTACK2",
    "SE_M_ENCORE",
    "SE_M_ENCORE2",
    "SE_M_BATON_PASS",
    "SE_M_MILK_DRINK",
    "SE_M_ATTRACT",
    "SE_M_ATTRACT2",
    "SE_M_MORNING_SUN",
    "SE_M_FLATTER",
    "SE_M_SAND_TOMB",
    "SE_M_GRASSWHISTLE",
    "SE_M_SPIT_UP",
    "SE_M_DIVE",
    "SE_M_EARTHQUAKE",
    "SE_M_TWISTER",
    "SE_M_SWEET_SCENT",
    "SE_M_YAWN",
    "SE_M_SKY_UPPERCUT",
    "SE_M_STAT_INCREASE",
    "SE_M_HEAT_WAVE",
    "SE_M_UPROAR",
    "SE_M_HAIL",
    "SE_M_COSMIC_POWER",
    "SE_M_TEETER_DANCE",
    "SE_M_STAT_DECREASE",
    "SE_M_HAZE",
    "SE_M_HYPER_BEAM2",
    "SE_RG_DOOR",
    "SE_RG_CARD_FLIP",
    "SE_RG_CARD_FLIPPING",
    "SE_RG_CARD_OPEN",
    "SE_RG_BAG_CURSOR",
    "SE_RG_BAG_POCKET",
    "SE_RG_BALL_CLICK",
    "SE_RG_SHOP",
    "SE_RG_SS_ANNE_HORN",
    "SE_RG_HELP_OPEN",
    "SE_RG_HELP_CLOSE",
    "SE_RG_HELP_ERROR",
    "SE_RG_DEOXYS_MOVE",
    "SE_RG_POKE_JUMP_SUCCESS",
    "SE_RG_POKE_JUMP_FAILURE",
    "SE_POKENAV_CALL",
    "SE_POKENAV_HANG_UP",
    "SE_ARENA_TIMEUP1",
    "SE_ARENA_TIMEUP2",
    "SE_PIKE_CURTAIN_CLOSE",
    "SE_PIKE_CURTAIN_OPEN",
    "SE_SUDOWOODO_SHAKE",
    "SE_DUMMY_1",
}

VANILLA_TILESETS = {
    "battle_arena",
    "battle_dome",
    "battle_factory",
    "battle_frontier",
    "battle_frontier_outside_east",
    "battle_frontier_outside_west",
    "battle_frontier_ranking_hall",
    "battle_palace",
    "battle_pike",
    "battle_pyramid",
    "battle_tent",
    "bike_shop",
    "brendans_mays_house",
    "cable_club",
    "cave",
    "contest",
    "dewford",
    "dewford_gym",
    "elite_four",
    "ever_grande",
    "facility",
    "fallarbor",
    "fortree",
    "fortree_gym",
    "generic_building",
    "inside_of_truck",
    "inside_ship",
    "island_harbor",
    "lab",
    "lavaridge",
    "lavaridge_gym",
    "lilycove",
    "lilycove_museum",
    "mauville",
    "mauville_game_corner",
    "mauville_gym",
    "meteor_falls",
    "mirage_tower",
    "mossdeep",
    "mossdeep_game_corner",
    "mossdeep_gym",
    "mystery_events_house",
    "navel_rock",
    "oceanic_museum",
    "pacifidlog",
    "petalburg",
    "petalburg_gym",
    "petalburg_leo_b",
    "petalburg_leo_bsnow",
    "pokemon_center",
    "pokemon_day_care",
    "pokemon_fan_club",
    "pokemon_school",
    "pretty_petal_flower_shop",
    "rustboro",
    "rustboro_gym",
    "rusturf_tunnel",
    "seashore_house",
    "secret_base",
    "shop",
    "slateport",
    "sootopolis",
    "sootopolis_gym",
    "trainer_hill",
    "trick_house_puzzle",
    "underwater",
    "union_room",
    "unused_1",
    "unused_2",
}


VANILLA_ITEM_ICONS = {
    "gItemIcon_AbilityCapsule",
    "gItemIcon_AbilityPatch",
    "gItemIcon_AbilityShield",
    "gItemIcon_Abomasite",
    "gItemIcon_Absolite",
    "gItemIcon_AbsorbBulb",
    "gItemIcon_AcroBike",
    "gItemIcon_AdamantCrystal",
    "gItemIcon_AdamantOrb",
    "gItemIcon_AdrenalineOrb",
    "gItemIcon_Aerodactylite",
    "gItemIcon_Aggronite",
    "gItemIcon_AguavBerry",
    "gItemIcon_AirBalloon",
    "gItemIcon_Alakazite",
    "gItemIcon_AloraichiumZ",
    "gItemIcon_Altarianite",
    "gItemIcon_Ampharosite",
    "gItemIcon_AmuletCoin",
    "gItemIcon_ApicotBerry",
    "gItemIcon_Apricorn",
    "gItemIcon_ArmorFossil",
    "gItemIcon_ArmoriteOre",
    "gItemIcon_AspearBerry",
    "gItemIcon_AssaultVest",
    "gItemIcon_Audinite",
    "gItemIcon_AuroraTicket",
    "gItemIcon_AuspiciousArmor",
    "gItemIcon_AuxBottle",
    "gItemIcon_AuxPowerguard",
    "gItemIcon_BabiriBerry",
    "gItemIcon_BalmMushroom",
    "gItemIcon_Banettite",
    "gItemIcon_BasementKey",
    "gItemIcon_BattleStatItem",
    "gItemIcon_BeadMail",
    "gItemIcon_BeastBall",
    "gItemIcon_Beedrillite",
    "gItemIcon_BelueBerry",
    "gItemIcon_BerryJuice",
    "gItemIcon_BerryPouch",
    "gItemIcon_BerrySweet",
    "gItemIcon_BerserkGene",
    "gItemIcon_Bicycle",
    "gItemIcon_BigBambooShoot",
    "gItemIcon_BigMalasada",
    "gItemIcon_BigMushroom",
    "gItemIcon_BigNugget",
    "gItemIcon_BigPearl",
    "gItemIcon_BigRoot",
    "gItemIcon_BikeVoucher",
    "gItemIcon_BindingBand",
    "gItemIcon_BlackAugurite",
    "gItemIcon_BlackBelt",
    "gItemIcon_BlackGlasses",
    "gItemIcon_BlackSludge",
    "gItemIcon_Blastoisinite",
    "gItemIcon_Blazikenite",
    "gItemIcon_BlueOrb",
    "gItemIcon_BlukBerry",
    "gItemIcon_BlunderPolicy",
    "gItemIcon_Bone",
    "gItemIcon_BoosterEnergy",
    "gItemIcon_BottleCap",
    "gItemIcon_BrightPowder",
    "gItemIcon_BugMemory",
    "gItemIcon_BuginiumZ",
    "gItemIcon_Cameruptite",
    "gItemIcon_CardKey",
    "gItemIcon_Casteliacone",
    "gItemIcon_CatchingCharm",
    "gItemIcon_CellBattery",
    "gItemIcon_Charcoal",
    "gItemIcon_CharizarditeX",
    "gItemIcon_CharizarditeY",
    "gItemIcon_ChartiBerry",
    "gItemIcon_CheriBerry",
    "gItemIcon_CherishBall",
    "gItemIcon_ChestoBerry",
    "gItemIcon_ChilanBerry",
    "gItemIcon_ChippedPot",
    "gItemIcon_ChoiceBand",
    "gItemIcon_ChoiceDumpling",
    "gItemIcon_ChoiceScarf",
    "gItemIcon_ChoiceSpecs",
    "gItemIcon_ChopleBerry",
    "gItemIcon_ClawFossil",
    "gItemIcon_CleanseTag",
    "gItemIcon_ClearAmulet",
    "gItemIcon_CloverSweet",
    "gItemIcon_CobaBerry",
    "gItemIcon_CoinCase",
    "gItemIcon_ColburBerry",
    "gItemIcon_ContestPass",
    "gItemIcon_CornerstoneMask",
    "gItemIcon_CornnBerry",
    "gItemIcon_CoverFossil",
    "gItemIcon_CovertCloak",
    "gItemIcon_CrackedPot",
    "gItemIcon_CustapBerry",
    "gItemIcon_DNASplicers",
    "gItemIcon_DampRock",
    "gItemIcon_DarkMemory",
    "gItemIcon_DarkiniumZ",
    "gItemIcon_DawnStone",
    "gItemIcon_DecidiumZ",
    "gItemIcon_DeepSeaScale",
    "gItemIcon_DeepSeaTooth",
    "gItemIcon_DestinyKnot",
    "gItemIcon_DevonParts",
    "gItemIcon_DevonScope",
    "gItemIcon_Diancite",
    "gItemIcon_DittoPowder",
    "gItemIcon_DiveBall",
    "gItemIcon_DomeFossil",
    "gItemIcon_DowsingMachine",
    "gItemIcon_DragonFang",
    "gItemIcon_DragonMemory",
    "gItemIcon_DragonScale",
    "gItemIcon_DragoniumZ",
    "gItemIcon_DreamBall",
    "gItemIcon_DreamMail",
    "gItemIcon_Drive",
    "gItemIcon_DubiousDisc",
    "gItemIcon_DurinBerry",
    "gItemIcon_DuskBall",
    "gItemIcon_DuskStone",
    "gItemIcon_DynamaxBand",
    "gItemIcon_DynamaxCandy",
    "gItemIcon_DyniteOre",
    "gItemIcon_EVFeather",
    "gItemIcon_EeviumZ",
    "gItemIcon_EjectButton",
    "gItemIcon_EjectPack",
    "gItemIcon_Electirizer",
    "gItemIcon_ElectricMemory",
    "gItemIcon_ElectriumZ",
    "gItemIcon_EnergyRoot",
    "gItemIcon_EnigmaBerry",
    "gItemIcon_EonTicket",
    "gItemIcon_EscapeRope",
    "gItemIcon_Ether",
    "gItemIcon_Everstone",
    "gItemIcon_Eviolite",
    "gItemIcon_ExpCandyL",
    "gItemIcon_ExpCandyM",
    "gItemIcon_ExpCandyS",
    "gItemIcon_ExpCandyXL",
    "gItemIcon_ExpCandyXS",
    "gItemIcon_ExpCharm",
    "gItemIcon_ExpShare",
    "gItemIcon_ExpertBelt",
    "gItemIcon_FabMail",
    "gItemIcon_FairiumZ",
    "gItemIcon_FairyFeather",
    "gItemIcon_FairyMemory",
    "gItemIcon_FameChecker",
    "gItemIcon_FastBall",
    "gItemIcon_FightingMemory",
    "gItemIcon_FightiniumZ",
    "gItemIcon_FigyBerry",
    "gItemIcon_FineRemedy",
    "gItemIcon_FireMemory",
    "gItemIcon_FireStone",
    "gItemIcon_FiriumZ",
    "gItemIcon_FlameOrb",
    "gItemIcon_FloatStone",
    "gItemIcon_FlowerSweet",
    "gItemIcon_FluffyTail",
    "gItemIcon_Flute",
    "gItemIcon_FlyingMemory",
    "gItemIcon_FlyiniumZ",
    "gItemIcon_FocusBand",
    "gItemIcon_FocusSash",
    "gItemIcon_FossilizedBird",
    "gItemIcon_FossilizedDino",
    "gItemIcon_FossilizedDrake",
    "gItemIcon_FossilizedFish",
    "gItemIcon_FreshWater",
    "gItemIcon_FriendBall",
    "gItemIcon_FullHeal",
    "gItemIcon_FullIncense",
    "gItemIcon_GalaricaCuff",
    "gItemIcon_GalaricaTwig",
    "gItemIcon_GalaricaWreath",
    "gItemIcon_Galladite",
    "gItemIcon_GanlonBerry",
    "gItemIcon_Garchompite",
    "gItemIcon_Gardevoirite",
    "gItemIcon_Gem",
    "gItemIcon_Gengarite",
    "gItemIcon_GhostMemory",
    "gItemIcon_GhostiumZ",
    "gItemIcon_GimmighoulCoin",
    "gItemIcon_Glalitite",
    "gItemIcon_GlimmeringCharm",
    "gItemIcon_GlitterMail",
    "gItemIcon_GoGoggles",
    "gItemIcon_GoldTeeth",
    "gItemIcon_GoodRod",
    "gItemIcon_Gracidea",
    "gItemIcon_GrassMemory",
    "gItemIcon_GrassiumZ",
    "gItemIcon_GreatBall",
    "gItemIcon_GrepaBerry",
    "gItemIcon_GripClaw",
    "gItemIcon_GriseousCore",
    "gItemIcon_GriseousOrb",
    "gItemIcon_GroundMemory",
    "gItemIcon_GroundiumZ",
    "gItemIcon_Gyaradosite",
    "gItemIcon_HM",
    "gItemIcon_HPUp",
    "gItemIcon_HabanBerry",
    "gItemIcon_HarborMail",
    "gItemIcon_HardStone",
    "gItemIcon_HealBall",
    "gItemIcon_HeartScale",
    "gItemIcon_HearthflameMask",
    "gItemIcon_HeatRock",
    "gItemIcon_HeavyBall",
    "gItemIcon_HeavyDutyBoots",
    "gItemIcon_HelixFossil",
    "gItemIcon_Heracronite",
    "gItemIcon_HondewBerry",
    "gItemIcon_Honey",
    "gItemIcon_Houndoominite",
    "gItemIcon_IapapaBerry",
    "gItemIcon_IceMemory",
    "gItemIcon_IceStone",
    "gItemIcon_IciumZ",
    "gItemIcon_IcyRock",
    "gItemIcon_InBattleHerb",
    "gItemIcon_InciniumZ",
    "gItemIcon_IronBall",
    "gItemIcon_JabocaBerry",
    "gItemIcon_JawFossil",
    "gItemIcon_JubilifeMuffin",
    "gItemIcon_Kangaskhanite",
    "gItemIcon_KasibBerry",
    "gItemIcon_KebiaBerry",
    "gItemIcon_KeeBerry",
    "gItemIcon_KelpsyBerry",
    "gItemIcon_KeyToRoom1",
    "gItemIcon_KeyToRoom2",
    "gItemIcon_KeyToRoom4",
    "gItemIcon_KeyToRoom6",
    "gItemIcon_KingsRock",
    "gItemIcon_KommoniumZ",
    "gItemIcon_LaggingTail",
    "gItemIcon_LansatBerry",
    "gItemIcon_LargePotion",
    "gItemIcon_Latiasite",
    "gItemIcon_Latiosite",
    "gItemIcon_LavaCookie",
    "gItemIcon_LaxIncense",
    "gItemIcon_LeadersCrest",
    "gItemIcon_LeafStone",
    "gItemIcon_Leek",
    "gItemIcon_Leftovers",
    "gItemIcon_Lemonade",
    "gItemIcon_LeppaBerry",
    "gItemIcon_Letter",
    "gItemIcon_LevelBall",
    "gItemIcon_LiechiBerry",
    "gItemIcon_LifeOrb",
    "gItemIcon_LiftKey",
    "gItemIcon_LightBall",
    "gItemIcon_LightClay",
    "gItemIcon_LinkingCord",
    "gItemIcon_LoadedDice",
    "gItemIcon_Lopunnite",
    "gItemIcon_LoveBall",
    "gItemIcon_LoveSweet",
    "gItemIcon_Lucarionite",
    "gItemIcon_LuckIncense",
    "gItemIcon_LuckyEgg",
    "gItemIcon_LuckyPunch",
    "gItemIcon_LumBerry",
    "gItemIcon_LuminousMoss",
    "gItemIcon_LumioseGalette",
    "gItemIcon_LunaliumZ",
    "gItemIcon_Lure",
    "gItemIcon_LureBall",
    "gItemIcon_LustrousGlobe",
    "gItemIcon_LustrousOrb",
    "gItemIcon_LuxuryBall",
    "gItemIcon_LycaniumZ",
    "gItemIcon_MachBike",
    "gItemIcon_MachoBrace",
    "gItemIcon_MagmaEmblem",
    "gItemIcon_Magmarizer",
    "gItemIcon_Magnet",
    "gItemIcon_MagoBerry",
    "gItemIcon_MagostBerry",
    "gItemIcon_MaliciousArmor",
    "gItemIcon_Manectite",
    "gItemIcon_MarangaBerry",
    "gItemIcon_MarshadiumZ",
    "gItemIcon_MasterBall",
    "gItemIcon_MasterpieceTeacup",
    "gItemIcon_Mawilite",
    "gItemIcon_MaxHoney",
    "gItemIcon_MaxMushrooms",
    "gItemIcon_MaxRevive",
    "gItemIcon_MechMail",
    "gItemIcon_Medichamite",
    "gItemIcon_MegaRing",
    "gItemIcon_Metagrossite",
    "gItemIcon_MetalAlloy",
    "gItemIcon_MetalCoat",
    "gItemIcon_Meteorite",
    "gItemIcon_Metronome",
    "gItemIcon_MewniumZ",
    "gItemIcon_MewtwoniteX",
    "gItemIcon_MewtwoniteY",
    "gItemIcon_MicleBerry",
    "gItemIcon_MimikiumZ",
    "gItemIcon_Mint",
    "gItemIcon_MiracleSeed",
    "gItemIcon_MirrorHerb",
    "gItemIcon_Mochi",
    "gItemIcon_MoomooMilk",
    "gItemIcon_MoonBall",
    "gItemIcon_MoonStone",
    "gItemIcon_Mulch",
    "gItemIcon_MuscleBand",
    "gItemIcon_MysticTicket",
    "gItemIcon_MysticWater",
    "gItemIcon_NanabBerry",
    "gItemIcon_NecrozmaFuser",
    "gItemIcon_Nectar",
    "gItemIcon_NestBall",
    "gItemIcon_NetBall",
    "gItemIcon_NeverMeltIce",
    "gItemIcon_NomelBerry",
    "gItemIcon_NormaliumZ",
    "gItemIcon_Nugget",
    "gItemIcon_OccaBerry",
    "gItemIcon_OddIncense",
    "gItemIcon_OddKeystone",
    "gItemIcon_OldAmber",
    "gItemIcon_OldGateau",
    "gItemIcon_OldRod",
    "gItemIcon_OldSeaMap",
    "gItemIcon_OranBerry",
    "gItemIcon_OrangeMail",
    "gItemIcon_OvalCharm",
    "gItemIcon_OvalStone",
    "gItemIcon_PPMax",
    "gItemIcon_PPUp",
    "gItemIcon_PamtreBerry",
    "gItemIcon_Parcel",
    "gItemIcon_ParkBall",
    "gItemIcon_PasshoBerry",
    "gItemIcon_PayapaBerry",
    "gItemIcon_Pearl",
    "gItemIcon_PearlString",
    "gItemIcon_PeatBlock",
    "gItemIcon_PechaBerry",
    "gItemIcon_PersimBerry",
    "gItemIcon_PetayaBerry",
    "gItemIcon_PewterCrunchies",
    "gItemIcon_Pidgeotite",
    "gItemIcon_PikaniumZ",
    "gItemIcon_PikashuniumZ",
    "gItemIcon_PinapBerry",
    "gItemIcon_Pinsirite",
    "gItemIcon_Plate",
    "gItemIcon_PlumeFossil",
    "gItemIcon_PoisonBarb",
    "gItemIcon_PoisonMemory",
    "gItemIcon_PoisoniumZ",
    "gItemIcon_PokeBall",
    "gItemIcon_PokeDoll",
    "gItemIcon_PokeFlute",
    "gItemIcon_PokeRadar",
    "gItemIcon_PokeToy",
    "gItemIcon_PokeblockCase",
    "gItemIcon_PokemonBoxLink",
    "gItemIcon_PokeshiDoll",
    "gItemIcon_PomegBerry",
    "gItemIcon_Potion",
    "gItemIcon_Powder",
    "gItemIcon_PowderJar",
    "gItemIcon_PowerAnklet",
    "gItemIcon_PowerBand",
    "gItemIcon_PowerBelt",
    "gItemIcon_PowerBracer",
    "gItemIcon_PowerHerb",
    "gItemIcon_PowerLens",
    "gItemIcon_PowerWeight",
    "gItemIcon_PremierBall",
    "gItemIcon_PrettyFeather",
    "gItemIcon_PrimariumZ",
    "gItemIcon_PrismScale",
    "gItemIcon_PrisonBottle",
    "gItemIcon_ProtectivePads",
    "gItemIcon_Protector",
    "gItemIcon_PsychicMemory",
    "gItemIcon_PsychiumZ",
    "gItemIcon_PunchingGlove",
    "gItemIcon_PureIncense",
    "gItemIcon_QualotBerry",
    "gItemIcon_QuestionMark",
    "gItemIcon_QuickBall",
    "gItemIcon_QuickClaw",
    "gItemIcon_RabutaBerry",
    "gItemIcon_RageCandyBar",
    "gItemIcon_RainbowPass",
    "gItemIcon_RareCandy",
    "gItemIcon_RawstBerry",
    "gItemIcon_RazorClaw",
    "gItemIcon_RazorFang",
    "gItemIcon_RazzBerry",
    "gItemIcon_ReaperCloth",
    "gItemIcon_RedCard",
    "gItemIcon_RedOrb",
    "gItemIcon_ReinsOfUnity",
    "gItemIcon_RelicBand",
    "gItemIcon_RelicCoin",
    "gItemIcon_RelicCrown",
    "gItemIcon_RelicStatue",
    "gItemIcon_RelicVase",
    "gItemIcon_Remedy",
    "gItemIcon_RepeatBall",
    "gItemIcon_Repel",
    "gItemIcon_RetroMail",
    "gItemIcon_ReturnToFieldArrow",
    "gItemIcon_RevealGlass",
    "gItemIcon_RevivalHerb",
    "gItemIcon_Revive",
    "gItemIcon_RibbonSweet",
    "gItemIcon_RindoBerry",
    "gItemIcon_RingTarget",
    "gItemIcon_RockIncense",
    "gItemIcon_RockMemory",
    "gItemIcon_RockiumZ",
    "gItemIcon_RockyHelmet",
    "gItemIcon_RoomService",
    "gItemIcon_RootFossil",
    "gItemIcon_RoseIncense",
    "gItemIcon_RoseliBerry",
    "gItemIcon_RotomCatalog",
    "gItemIcon_RowapBerry",
    "gItemIcon_RustedShield",
    "gItemIcon_RustedSword",
    "gItemIcon_SSTicket",
    "gItemIcon_Sablenite",
    "gItemIcon_Sachet",
    "gItemIcon_SafariBall",
    "gItemIcon_SafetyGoggles",
    "gItemIcon_SailFossil",
    "gItemIcon_SalacBerry",
    "gItemIcon_Salamencite",
    "gItemIcon_Sand",
    "gItemIcon_Scanner",
    "gItemIcon_Scarf",
    "gItemIcon_Sceptilite",
    "gItemIcon_Scizorite",
    "gItemIcon_ScopeLens",
    "gItemIcon_ScrollOfDarkness",
    "gItemIcon_ScrollOfWaters",
    "gItemIcon_SeaIncense",
    "gItemIcon_SecretKey",
    "gItemIcon_ShadowMail",
    "gItemIcon_ShalourSable",
    "gItemIcon_Shard",
    "gItemIcon_SharpBeak",
    "gItemIcon_Sharpedonite",
    "gItemIcon_ShedShell",
    "gItemIcon_ShellBell",
    "gItemIcon_ShinyCharm",
    "gItemIcon_ShinyStone",
    "gItemIcon_ShoalShell",
    "gItemIcon_ShucaBerry",
    "gItemIcon_SilkScarf",
    "gItemIcon_SilphScope",
    "gItemIcon_SilverPowder",
    "gItemIcon_SitrusBerry",
    "gItemIcon_SkullFossil",
    "gItemIcon_Slowbronite",
    "gItemIcon_SmokeBall",
    "gItemIcon_SmoothRock",
    "gItemIcon_SnorliumZ",
    "gItemIcon_Snowball",
    "gItemIcon_SodaPop",
    "gItemIcon_SolganiumZ",
    "gItemIcon_SootSack",
    "gItemIcon_SootheBell",
    "gItemIcon_SoulDew",
    "gItemIcon_SpellTag",
    "gItemIcon_SpelonBerry",
    "gItemIcon_SportBall",
    "gItemIcon_StableMulch",
    "gItemIcon_StarPiece",
    "gItemIcon_StarSweet",
    "gItemIcon_StarfBerry",
    "gItemIcon_StatusHeal",
    "gItemIcon_SteelMemory",
    "gItemIcon_SteeliumZ",
    "gItemIcon_Steelixite",
    "gItemIcon_StellarTeraShard",
    "gItemIcon_StickyBarb",
    "gItemIcon_StorageKey",
    "gItemIcon_StrangeBall",
    "gItemIcon_StrangeSouvenir",
    "gItemIcon_StrawberrySweet",
    "gItemIcon_SunStone",
    "gItemIcon_SuperRod",
    "gItemIcon_SuperbRemedy",
    "gItemIcon_Swampertite",
    "gItemIcon_SwapSnack",
    "gItemIcon_SweetApple",
    "gItemIcon_SweetHeart",
    "gItemIcon_SyrupyApple",
    "gItemIcon_TM",
    "gItemIcon_TMCase",
    "gItemIcon_TamatoBerry",
    "gItemIcon_TangaBerry",
    "gItemIcon_TapuniumZ",
    "gItemIcon_TartApple",
    "gItemIcon_Tea",
    "gItemIcon_TeachyTV",
    "gItemIcon_TeraOrb",
    "gItemIcon_TeraShard",
    "gItemIcon_TerrainExtender",
    "gItemIcon_TerrainSeed",
    "gItemIcon_ThroatSpray",
    "gItemIcon_ThunderStone",
    "gItemIcon_TimerBall",
    "gItemIcon_TinyBambooShoot",
    "gItemIcon_TinyMushroom",
    "gItemIcon_TownMap",
    "gItemIcon_ToxicOrb",
    "gItemIcon_TriPass",
    "gItemIcon_TropicMail",
    "gItemIcon_TwiceSpicedRadish",
    "gItemIcon_TwistedSpoon",
    "gItemIcon_TypeGem",
    "gItemIcon_Tyranitarite",
    "gItemIcon_UltraBall",
    "gItemIcon_UltranecroziumZ",
    "gItemIcon_UnremarkableTeacup",
    "gItemIcon_Upgrade",
    "gItemIcon_UtilityUmbrella",
    "gItemIcon_Venusaurite",
    "gItemIcon_Vitamin",
    "gItemIcon_VsSeeker",
    "gItemIcon_WacanBerry",
    "gItemIcon_WailmerPail",
    "gItemIcon_WaterMemory",
    "gItemIcon_WaterStone",
    "gItemIcon_WateriumZ",
    "gItemIcon_WatmelBerry",
    "gItemIcon_WaveIncense",
    "gItemIcon_WaveMail",
    "gItemIcon_WeaknessPolicy",
    "gItemIcon_WellspringMask",
    "gItemIcon_WepearBerry",
    "gItemIcon_WhippedDream",
    "gItemIcon_WideLens",
    "gItemIcon_WikiBerry",
    "gItemIcon_WiseGlasses",
    "gItemIcon_WishingPiece",
    "gItemIcon_WoodMail",
    "gItemIcon_YacheBerry",
    "gItemIcon_ZPowerRing",
    "gItemIcon_ZRing",
    "gItemIcon_ZoomLens",
    "gItemIcon_ZygardeCube",
}

# Verified against pokeemerald-expansion include/constants/trainers.h
# (stable across all expansion versions — 93 entries, IDs 0-92).
VANILLA_TRAINER_PICS = {
    "TRAINER_PIC_HIKER", "TRAINER_PIC_AQUA_GRUNT_M",
    "TRAINER_PIC_POKEMON_BREEDER_F", "TRAINER_PIC_COOLTRAINER_M",
    "TRAINER_PIC_BIRD_KEEPER", "TRAINER_PIC_COLLECTOR",
    "TRAINER_PIC_AQUA_GRUNT_F", "TRAINER_PIC_SWIMMER_M",
    "TRAINER_PIC_MAGMA_GRUNT_M", "TRAINER_PIC_EXPERT_M",
    "TRAINER_PIC_AQUA_ADMIN_M", "TRAINER_PIC_BLACK_BELT",
    "TRAINER_PIC_AQUA_ADMIN_F", "TRAINER_PIC_AQUA_LEADER_ARCHIE",
    "TRAINER_PIC_HEX_MANIAC", "TRAINER_PIC_AROMA_LADY",
    "TRAINER_PIC_RUIN_MANIAC", "TRAINER_PIC_INTERVIEWER",
    "TRAINER_PIC_TUBER_F", "TRAINER_PIC_TUBER_M",
    "TRAINER_PIC_COOLTRAINER_F", "TRAINER_PIC_LADY",
    "TRAINER_PIC_BEAUTY", "TRAINER_PIC_RICH_BOY",
    "TRAINER_PIC_EXPERT_F", "TRAINER_PIC_POKEMANIAC",
    "TRAINER_PIC_MAGMA_GRUNT_F", "TRAINER_PIC_GUITARIST",
    "TRAINER_PIC_KINDLER", "TRAINER_PIC_CAMPER",
    "TRAINER_PIC_PICNICKER", "TRAINER_PIC_BUG_MANIAC",
    "TRAINER_PIC_POKEMON_BREEDER_M", "TRAINER_PIC_PSYCHIC_M",
    "TRAINER_PIC_PSYCHIC_F", "TRAINER_PIC_GENTLEMAN",
    "TRAINER_PIC_ELITE_FOUR_SIDNEY", "TRAINER_PIC_ELITE_FOUR_PHOEBE",
    "TRAINER_PIC_ELITE_FOUR_GLACIA", "TRAINER_PIC_ELITE_FOUR_DRAKE",
    "TRAINER_PIC_LEADER_ROXANNE", "TRAINER_PIC_LEADER_BRAWLY",
    "TRAINER_PIC_LEADER_WATTSON", "TRAINER_PIC_LEADER_FLANNERY",
    "TRAINER_PIC_LEADER_NORMAN", "TRAINER_PIC_LEADER_WINONA",
    "TRAINER_PIC_LEADER_TATE_AND_LIZA", "TRAINER_PIC_LEADER_JUAN",
    "TRAINER_PIC_SCHOOL_KID_M", "TRAINER_PIC_SCHOOL_KID_F",
    "TRAINER_PIC_SR_AND_JR", "TRAINER_PIC_POKEFAN_M",
    "TRAINER_PIC_POKEFAN_F", "TRAINER_PIC_YOUNGSTER",
    "TRAINER_PIC_CHAMPION_WALLACE", "TRAINER_PIC_FISHERMAN",
    "TRAINER_PIC_CYCLING_TRIATHLETE_M", "TRAINER_PIC_CYCLING_TRIATHLETE_F",
    "TRAINER_PIC_RUNNING_TRIATHLETE_M", "TRAINER_PIC_RUNNING_TRIATHLETE_F",
    "TRAINER_PIC_SWIMMING_TRIATHLETE_M", "TRAINER_PIC_SWIMMING_TRIATHLETE_F",
    "TRAINER_PIC_DRAGON_TAMER", "TRAINER_PIC_NINJA_BOY",
    "TRAINER_PIC_BATTLE_GIRL", "TRAINER_PIC_PARASOL_LADY",
    "TRAINER_PIC_SWIMMER_F", "TRAINER_PIC_TWINS",
    "TRAINER_PIC_SAILOR", "TRAINER_PIC_MAGMA_ADMIN",
    "TRAINER_PIC_WALLY", "TRAINER_PIC_BRENDAN",
    "TRAINER_PIC_MAY", "TRAINER_PIC_BUG_CATCHER",
    "TRAINER_PIC_POKEMON_RANGER_M", "TRAINER_PIC_POKEMON_RANGER_F",
    "TRAINER_PIC_MAGMA_LEADER_MAXIE", "TRAINER_PIC_LASS",
    "TRAINER_PIC_YOUNG_COUPLE", "TRAINER_PIC_OLD_COUPLE",
    "TRAINER_PIC_SIS_AND_BRO", "TRAINER_PIC_STEVEN",
    "TRAINER_PIC_SALON_MAIDEN_ANABEL", "TRAINER_PIC_DOME_ACE_TUCKER",
    "TRAINER_PIC_PALACE_MAVEN_SPENSER", "TRAINER_PIC_ARENA_TYCOON_GRETA",
    "TRAINER_PIC_FACTORY_HEAD_NOLAND", "TRAINER_PIC_PIKE_QUEEN_LUCY",
    "TRAINER_PIC_PYRAMID_KING_BRANDON", "TRAINER_PIC_RED",
    "TRAINER_PIC_LEAF", "TRAINER_PIC_RS_BRENDAN",
    "TRAINER_PIC_RS_MAY",
}

# Verified against pokeemerald-expansion include/constants/event_objects.h
# (stable across expansion versions — 264 entries including VAR_0-F).
VANILLA_OVERWORLD_SPRITES = {
    "OBJ_EVENT_GFX_BRENDAN_NORMAL", "OBJ_EVENT_GFX_BRENDAN_MACH_BIKE",
    "OBJ_EVENT_GFX_BRENDAN_SURFING", "OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE",
    "OBJ_EVENT_GFX_QUINTY_PLUMP", "OBJ_EVENT_GFX_NINJA_BOY",
    "OBJ_EVENT_GFX_TWIN", "OBJ_EVENT_GFX_BOY_1",
    "OBJ_EVENT_GFX_GIRL_1", "OBJ_EVENT_GFX_BOY_2",
    "OBJ_EVENT_GFX_GIRL_2", "OBJ_EVENT_GFX_LITTLE_BOY",
    "OBJ_EVENT_GFX_LITTLE_GIRL", "OBJ_EVENT_GFX_BOY_3",
    "OBJ_EVENT_GFX_GIRL_3", "OBJ_EVENT_GFX_RICH_BOY",
    "OBJ_EVENT_GFX_WOMAN_1", "OBJ_EVENT_GFX_FAT_MAN",
    "OBJ_EVENT_GFX_POKEFAN_F", "OBJ_EVENT_GFX_MAN_1",
    "OBJ_EVENT_GFX_WOMAN_2", "OBJ_EVENT_GFX_EXPERT_M",
    "OBJ_EVENT_GFX_EXPERT_F", "OBJ_EVENT_GFX_MAN_2",
    "OBJ_EVENT_GFX_WOMAN_3", "OBJ_EVENT_GFX_POKEFAN_M",
    "OBJ_EVENT_GFX_WOMAN_4", "OBJ_EVENT_GFX_COOK",
    "OBJ_EVENT_GFX_LINK_RECEPTIONIST", "OBJ_EVENT_GFX_OLD_MAN",
    "OBJ_EVENT_GFX_OLD_WOMAN", "OBJ_EVENT_GFX_CAMPER",
    "OBJ_EVENT_GFX_PICNICKER", "OBJ_EVENT_GFX_MAN_3",
    "OBJ_EVENT_GFX_WOMAN_5", "OBJ_EVENT_GFX_YOUNGSTER",
    "OBJ_EVENT_GFX_BUG_CATCHER", "OBJ_EVENT_GFX_PSYCHIC_M",
    "OBJ_EVENT_GFX_SCHOOL_KID_M", "OBJ_EVENT_GFX_MANIAC",
    "OBJ_EVENT_GFX_HEX_MANIAC", "OBJ_EVENT_GFX_RAYQUAZA_STILL",
    "OBJ_EVENT_GFX_SWIMMER_M", "OBJ_EVENT_GFX_SWIMMER_F",
    "OBJ_EVENT_GFX_BLACK_BELT", "OBJ_EVENT_GFX_BEAUTY",
    "OBJ_EVENT_GFX_SCIENTIST_1", "OBJ_EVENT_GFX_LASS",
    "OBJ_EVENT_GFX_GENTLEMAN", "OBJ_EVENT_GFX_SAILOR",
    "OBJ_EVENT_GFX_FISHERMAN", "OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M",
    "OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F", "OBJ_EVENT_GFX_TUBER_F",
    "OBJ_EVENT_GFX_TUBER_M", "OBJ_EVENT_GFX_HIKER",
    "OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M", "OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F",
    "OBJ_EVENT_GFX_NURSE", "OBJ_EVENT_GFX_ITEM_BALL",
    "OBJ_EVENT_GFX_BERRY_TREE", "OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES",
    "OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES", "OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE",
    "OBJ_EVENT_GFX_PROF_BIRCH", "OBJ_EVENT_GFX_MAN_4",
    "OBJ_EVENT_GFX_MAN_5", "OBJ_EVENT_GFX_REPORTER_M",
    "OBJ_EVENT_GFX_REPORTER_F", "OBJ_EVENT_GFX_BARD",
    "OBJ_EVENT_GFX_ANABEL", "OBJ_EVENT_GFX_TUCKER",
    "OBJ_EVENT_GFX_GRETA", "OBJ_EVENT_GFX_SPENSER",
    "OBJ_EVENT_GFX_NOLAND", "OBJ_EVENT_GFX_LUCY",
    "OBJ_EVENT_GFX_UNUSED_NATU_DOLL", "OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL",
    "OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL", "OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL",
    "OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL", "OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL",
    "OBJ_EVENT_GFX_CUTTABLE_TREE", "OBJ_EVENT_GFX_MART_EMPLOYEE",
    "OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN", "OBJ_EVENT_GFX_TEALA",
    "OBJ_EVENT_GFX_BREAKABLE_ROCK", "OBJ_EVENT_GFX_PUSHABLE_BOULDER",
    "OBJ_EVENT_GFX_MR_BRINEYS_BOAT", "OBJ_EVENT_GFX_MAY_NORMAL",
    "OBJ_EVENT_GFX_MAY_MACH_BIKE", "OBJ_EVENT_GFX_MAY_ACRO_BIKE",
    "OBJ_EVENT_GFX_MAY_SURFING", "OBJ_EVENT_GFX_MAY_FIELD_MOVE",
    "OBJ_EVENT_GFX_TRUCK", "OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX",
    "OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY", "OBJ_EVENT_GFX_BIRCHS_BAG",
    "OBJ_EVENT_GFX_ZIGZAGOON_1", "OBJ_EVENT_GFX_ARTIST",
    "OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL", "OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE",
    "OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE", "OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING",
    "OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE", "OBJ_EVENT_GFX_RIVAL_MAY_NORMAL",
    "OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE", "OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE",
    "OBJ_EVENT_GFX_RIVAL_MAY_SURFING", "OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE",
    "OBJ_EVENT_GFX_CAMERAMAN", "OBJ_EVENT_GFX_BRENDAN_UNDERWATER",
    "OBJ_EVENT_GFX_MAY_UNDERWATER", "OBJ_EVENT_GFX_MOVING_BOX",
    "OBJ_EVENT_GFX_CABLE_CAR", "OBJ_EVENT_GFX_SCIENTIST_2",
    "OBJ_EVENT_GFX_DEVON_EMPLOYEE", "OBJ_EVENT_GFX_AQUA_MEMBER_M",
    "OBJ_EVENT_GFX_AQUA_MEMBER_F", "OBJ_EVENT_GFX_MAGMA_MEMBER_M",
    "OBJ_EVENT_GFX_MAGMA_MEMBER_F", "OBJ_EVENT_GFX_SIDNEY",
    "OBJ_EVENT_GFX_PHOEBE", "OBJ_EVENT_GFX_GLACIA",
    "OBJ_EVENT_GFX_DRAKE", "OBJ_EVENT_GFX_ROXANNE",
    "OBJ_EVENT_GFX_BRAWLY", "OBJ_EVENT_GFX_WATTSON",
    "OBJ_EVENT_GFX_FLANNERY", "OBJ_EVENT_GFX_NORMAN",
    "OBJ_EVENT_GFX_WINONA", "OBJ_EVENT_GFX_LIZA",
    "OBJ_EVENT_GFX_TATE", "OBJ_EVENT_GFX_WALLACE",
    "OBJ_EVENT_GFX_STEVEN", "OBJ_EVENT_GFX_WALLY",
    "OBJ_EVENT_GFX_LITTLE_BOY_3", "OBJ_EVENT_GFX_BRENDAN_FISHING",
    "OBJ_EVENT_GFX_MAY_FISHING", "OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN",
    "OBJ_EVENT_GFX_SS_TIDAL", "OBJ_EVENT_GFX_SUBMARINE_SHADOW",
    "OBJ_EVENT_GFX_PICHU_DOLL", "OBJ_EVENT_GFX_PIKACHU_DOLL",
    "OBJ_EVENT_GFX_MARILL_DOLL", "OBJ_EVENT_GFX_TOGEPI_DOLL",
    "OBJ_EVENT_GFX_CYNDAQUIL_DOLL", "OBJ_EVENT_GFX_CHIKORITA_DOLL",
    "OBJ_EVENT_GFX_TOTODILE_DOLL", "OBJ_EVENT_GFX_JIGGLYPUFF_DOLL",
    "OBJ_EVENT_GFX_MEOWTH_DOLL", "OBJ_EVENT_GFX_CLEFAIRY_DOLL",
    "OBJ_EVENT_GFX_DITTO_DOLL", "OBJ_EVENT_GFX_SMOOCHUM_DOLL",
    "OBJ_EVENT_GFX_TREECKO_DOLL", "OBJ_EVENT_GFX_TORCHIC_DOLL",
    "OBJ_EVENT_GFX_MUDKIP_DOLL", "OBJ_EVENT_GFX_DUSKULL_DOLL",
    "OBJ_EVENT_GFX_WYNAUT_DOLL", "OBJ_EVENT_GFX_BALTOY_DOLL",
    "OBJ_EVENT_GFX_KECLEON_DOLL", "OBJ_EVENT_GFX_AZURILL_DOLL",
    "OBJ_EVENT_GFX_SKITTY_DOLL", "OBJ_EVENT_GFX_SWABLU_DOLL",
    "OBJ_EVENT_GFX_GULPIN_DOLL", "OBJ_EVENT_GFX_LOTAD_DOLL",
    "OBJ_EVENT_GFX_SEEDOT_DOLL", "OBJ_EVENT_GFX_PIKA_CUSHION",
    "OBJ_EVENT_GFX_ROUND_CUSHION", "OBJ_EVENT_GFX_KISS_CUSHION",
    "OBJ_EVENT_GFX_ZIGZAG_CUSHION", "OBJ_EVENT_GFX_SPIN_CUSHION",
    "OBJ_EVENT_GFX_DIAMOND_CUSHION", "OBJ_EVENT_GFX_BALL_CUSHION",
    "OBJ_EVENT_GFX_GRASS_CUSHION", "OBJ_EVENT_GFX_FIRE_CUSHION",
    "OBJ_EVENT_GFX_WATER_CUSHION", "OBJ_EVENT_GFX_BIG_SNORLAX_DOLL",
    "OBJ_EVENT_GFX_BIG_RHYDON_DOLL", "OBJ_EVENT_GFX_BIG_LAPRAS_DOLL",
    "OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL", "OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL",
    "OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL", "OBJ_EVENT_GFX_BIG_WAILMER_DOLL",
    "OBJ_EVENT_GFX_BIG_REGIROCK_DOLL", "OBJ_EVENT_GFX_BIG_REGICE_DOLL",
    "OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL", "OBJ_EVENT_GFX_LATIAS",
    "OBJ_EVENT_GFX_LATIOS", "OBJ_EVENT_GFX_GAMEBOY_KID",
    "OBJ_EVENT_GFX_CONTEST_JUDGE", "OBJ_EVENT_GFX_BRENDAN_WATERING",
    "OBJ_EVENT_GFX_MAY_WATERING", "OBJ_EVENT_GFX_BRENDAN_DECORATING",
    "OBJ_EVENT_GFX_MAY_DECORATING", "OBJ_EVENT_GFX_ARCHIE",
    "OBJ_EVENT_GFX_MAXIE", "OBJ_EVENT_GFX_KYOGRE_FRONT",
    "OBJ_EVENT_GFX_GROUDON_FRONT", "OBJ_EVENT_GFX_FOSSIL",
    "OBJ_EVENT_GFX_REGIROCK", "OBJ_EVENT_GFX_REGICE",
    "OBJ_EVENT_GFX_REGISTEEL", "OBJ_EVENT_GFX_SKITTY",
    "OBJ_EVENT_GFX_KECLEON", "OBJ_EVENT_GFX_KYOGRE_ASLEEP",
    "OBJ_EVENT_GFX_GROUDON_ASLEEP", "OBJ_EVENT_GFX_RAYQUAZA",
    "OBJ_EVENT_GFX_ZIGZAGOON_2", "OBJ_EVENT_GFX_PIKACHU",
    "OBJ_EVENT_GFX_AZUMARILL", "OBJ_EVENT_GFX_WINGULL",
    "OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW", "OBJ_EVENT_GFX_TUBER_M_SWIMMING",
    "OBJ_EVENT_GFX_AZURILL", "OBJ_EVENT_GFX_MOM",
    "OBJ_EVENT_GFX_LINK_BRENDAN", "OBJ_EVENT_GFX_LINK_MAY",
    "OBJ_EVENT_GFX_JUAN", "OBJ_EVENT_GFX_SCOTT",
    "OBJ_EVENT_GFX_POOCHYENA", "OBJ_EVENT_GFX_KYOGRE_SIDE",
    "OBJ_EVENT_GFX_GROUDON_SIDE", "OBJ_EVENT_GFX_MYSTERY_GIFT_MAN",
    "OBJ_EVENT_GFX_TRICK_HOUSE_STATUE", "OBJ_EVENT_GFX_KIRLIA",
    "OBJ_EVENT_GFX_DUSCLOPS", "OBJ_EVENT_GFX_UNION_ROOM_NURSE",
    "OBJ_EVENT_GFX_SUDOWOODO", "OBJ_EVENT_GFX_MEW",
    "OBJ_EVENT_GFX_RED", "OBJ_EVENT_GFX_LEAF",
    "OBJ_EVENT_GFX_DEOXYS", "OBJ_EVENT_GFX_DEOXYS_TRIANGLE",
    "OBJ_EVENT_GFX_BRANDON", "OBJ_EVENT_GFX_LINK_RS_BRENDAN",
    "OBJ_EVENT_GFX_LINK_RS_MAY", "OBJ_EVENT_GFX_LUGIA",
    "OBJ_EVENT_GFX_HOOH", "OBJ_EVENT_GFX_GOLD_ITEM_BALL",
    "OBJ_EVENT_GFX_MEGA_STONE", "OBJ_EVENT_GFX_GAMECUBE",
    "OBJ_EVENT_GFX_LASS_HGSS", "OBJ_EVENT_GFX_BREEDER_F_HGSS",
    "OBJ_EVENT_GFX_HEX_MANIAC_ORAS", "OBJ_EVENT_GFX_ROCKET_GRUNT_F_HGSS",
    "OBJ_EVENT_GFX_MAY_RUNNING", "OBJ_EVENT_GFX_MAY_SNOW_DRIFT",
    "OBJ_EVENT_GFX_VAR_0", "OBJ_EVENT_GFX_VAR_1",
    "OBJ_EVENT_GFX_VAR_2", "OBJ_EVENT_GFX_VAR_3",
    "OBJ_EVENT_GFX_VAR_4", "OBJ_EVENT_GFX_VAR_5",
    "OBJ_EVENT_GFX_VAR_6", "OBJ_EVENT_GFX_VAR_7",
    "OBJ_EVENT_GFX_VAR_8", "OBJ_EVENT_GFX_VAR_9",
    "OBJ_EVENT_GFX_VAR_A", "OBJ_EVENT_GFX_VAR_B",
    "OBJ_EVENT_GFX_VAR_C", "OBJ_EVENT_GFX_VAR_D",
    "OBJ_EVENT_GFX_VAR_E", "OBJ_EVENT_GFX_VAR_F",
    "OBJ_EVENT_GFX_POKE_BALL", "OBJ_EVENT_GFX_OW_MON",
    "OBJ_EVENT_GFX_LIGHT_SPRITE", "OBJ_EVENT_GFX_APRICORN_TREE",
}
